package com.vacuumlabs.wadzpay.common

class ErrorCodes {
    companion object {
        const val TOKEN_EXPIRED = "TOKEN_EXPIRED"
        const val REFUND_FIAT_TYPE_AND_TRANSACTION_FIAT_TYPE_SHOULD_BE_SAME =
            "REFUND_FIAT_TYPE_AND_TRANSACTION_FIAT_TYPE_SHOULD_BE_SAME"

        // validation
        const val INVALID_INPUT_FORMAT = "INVALID_INPUT_FORMAT"
        const val INVALID_SIGNATURE = "INVALID_SIGNATURE"

        // otp request and verification
        const val INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER"
        const val UNKNOWN_TWILIO_ERROR = "UNKNOWN_TWILIO_ERROR"
        const val INCORRECT_CODE = "INCORRECT_CODE"
        const val NO_DATA_SENT = "NO_DATA_SENT"
        // registration
        const val INVALID_EMAIL = "INVALID_EMAIL"
        const val INVALID_PASSWORD = "INVALID_PASSWORD"
        const val VERIFICATION_NOT_FOUND = "VERIFICATION_NOT_FOUND"
        const val EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
        const val EMAIL_DOES_NOT_EXISTS = "EMAIL_DOES_NOT_EXISTS"
        const val UNVERIFIED_PHONE_NUMBER = "UNVERIFIED_PHONE_NUMBER"
        const val PHONE_NUMBER_ALREADY_EXISTS = "PHONE_NUMBER_ALREADY_EXISTS"
        const val PHONE_NUMBER_DOES_NOT_EXISTS = "PHONE_NUMBER_DOES_NOT_EXISTS"
        const val PHONE_NUMBER_ALREADY_VERIFIED = "PHONE_NUMBER_ALREADY_VERIFIED"
        const val CUSTOMER_ID_ALREADY_EXISTS = "CUSTOMER_ID_ALREADY_EXISTS"
        const val UNKNOWN_SEON_ERROR = "UNKNOWN_SEON_ERROR"
        const val FRAUDULENT_USER = "FRAUDULENT_USER"

        // merchant transactions
        const val INVALID_AMOUNT_TOO_MANY_DECIMAL_PLACES = "INVALID_AMOUNT_TOO_MANY_DECIMAL_PLACES"
        const val INVALID_AMOUNT_NEGATIVE_OR_ZERO = "INVALID_AMOUNT_NEGATIVE_OR_ZERO"
        const val AFTER_DEDUCTING_FEE_FINAL_AMOUNT_IS_ZERO_OR_NEGATIVE =
            "AFTER_DEDUCTING_FEE_FINAL_AMOUNT_IS_ZERO_OR_NEGATIVE"
        const val INVALID_AMOUNT_SUPPORT_MORE_THAN_FIVE = "INVALID_AMOUNT_SUPPORT_MORE_THAN_FIVE"
        const val INVALID_REFUND_MODE_TYPE_AS_CASH = "INVALID_REFUND_MODE_TYPE_AS_CASH"
        const val INVALID_CASH_REFUND_MODE_SHOULD_BE_WALLET_MODE = "INVALID_CASH_REFUND_MODE_SHOULD_BE_WALLET_MODE"
        const val REASON_FOR_REFUND_IS_MANDATORY = "REASON_FOR_REFUND_IS_MANDATORY"
        const val UNSUPPORTED_ETH_OR_USDT_WALLET_ADDRESS = "UNSUPPORTED_ETH_OR_USDT_WALLET_ADDRESS"
        const val REFUND_IN_TEST_AND_DEV_SHOULD_BE_BTC = "REFUND_IN_TEST_AND_DEV_SHOULD_BE_BTC"
        const val REFUND_DIGITAL_CURRENCY_TYPE_SHOULD_BE_USDT = "REFUND_DIGITAL_CURRENCY_TYPE_SHOULD_BE_USDT"
        const val REFUND_WALLET_ADDRESS_IS_EMPTY = "REFUND_WALLET_ADDRESS_IS_EMPTY"
        const val REFUND_BALANCE_AMOUNT_IS_LESS_THAN_REFUND_AMOUNT = "REFUND_BALANCE_AMOUNT_IS_LESS_THAN_REFUND_AMOUNT"
        const val DESCRIPTION_IS_MANDATORY_FIELD = "DESCRIPTION_IS_MANDATORY_FIELD"
        const val API_KEY_ALREADY_INVALID = "API_KEY_ALREADY_INVALID"
        const val API_KEY_DOES_NOT_EXIST = "API_KEY_DOES_NOT_EXIST"
        const val ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
        const val ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"
        const val SUBACCOUNT_NOT_FOUND = "SUBACCOUNT_NOT_FOUND"
        const val INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
        const val MERCHANT_NOT_FOUND = "MERCHANT_NOT_FOUND"
        const val INVALID_POS_ID = "INVALID_POS_ID"
        const val MERCHANT_ALREADY_EXISTS = "MERCHANT_ALREADY_EXISTS"
        const val EXPIRED_ORDER = "EXPIRED_ORDER"
        const val PROCESSED_ORDER = "PROCESSED_ORDER"
        const val CANCELLED_ORDER = "CANCELLED_ORDER"
        const val FAILED_ORDER = "FAILED_ORDER"
        const val INCORRECT_TARGET_EMAIL = "INCORRECT_TARGET_EMAIL"
        const val DUPLICATE_EXTERNAL_TRX_ID = "DUPLICATE_EXTERNAL_TRX_ID"
        const val INVALID_ASSET_TYPE = "INVALID_ASSET_TYPE"
        const val COUNTRY_CODE_OR_TIME_ZONE_MISSING = "COUNTRY_CODE_OR_TIME_ZONE_MISSING"
        const val MOBILE_OR_EMAIL_ANY_ONE_REQUIRED = "MOBILE_OR_EMAIL_ANY_ONE_REQUIRED"
        const val DATE_SHOULD_NOT_BE_FUTURE_DATE = "DATE_SHOULD_NOT_BE_FUTURE_DATE"
        const val TRANSACTION_IS_ALREADY_PAID = "TRANSACTION_IS_ALREADY_PAID"
        const val TRANSACTION_IS_ALREADY_SETTLED_NOT_REFUND_AGAIN = "TRANSACTION_IS_ALREADY_SETTLED_NOT_REFUND_AGAIN"
        const val NO_REFUND_TRANSACTION_FOR_APPROVAL = "NO_REFUND_TRANSACTION_FOR_APPROVAL"
        const val NO_REFUND_TRANSACTION_FOR_HOLD = "NO_REFUND_TRANSACTION_FOR_HOLD"
        const val TRANSACTION_IS_ALREADY_REJECTED_NOT_REFUND_AGAIN = "TRANSACTION_IS_ALREADY_REJECTED_NOT_REFUND_AGAIN"
        const val TRANSACTION_IS_ALREADY_ACCEPTED_NOT_ACCEPTED_AGAIN =
            "TRANSACTION_IS_ALREADY_ACCEPTED_NOT_ACCEPTED_AGAIN"
        const val TRANSACTION_NOT_MATCHING_REFUND_AMOUNT_FIAT = "TRANSACTION_NOT_MATCHING_REFUND_AMOUNT_FIAT"
        const val TRANSACTION_NOT_MATCHING_REFUND_AMOUNT_DIGITAL = "TRANSACTION_NOT_MATCHING_REFUND_AMOUNT_DIGITAL"
        const val TRANSACTION_NOT_MATCHING_REFUND_USER_NAME = "TRANSACTION_NOT_MATCHING_REFUND_USER_NAME"
        const val TRANSACTION_NOT_MATCHING_REFUND_USER_MOBILE = "TRANSACTION_NOT_MATCHING_REFUND_USER_MOBILE"
        const val TRANSACTION_NOT_MATCHING_REFUND_USER_EMAIL = "TRANSACTION_NOT_MATCHING_REFUND_USER_EMAIL"
        const val TRANSACTION_NOT_MATCHING_REFUND_DIGITAL_TYPE = "TRANSACTION_NOT_MATCHING_REFUND_DIGITAL_TYPE"
        const val TRANSACTION_NOT_MATCHING_REFUND_FIAT_TYPE = "TRANSACTION_NOT_MATCHING_REFUND_FIAT_TYPE"
        const val TRANSACTION_NOT_MATCHING_REFUND_MODE = "TRANSACTION_NOT_MATCHING_REFUND_MODE"
        const val TRANSACTION_REFUND_TYPE_IS_WALLET_AMOUNT_SHOULD_MORE_THAN_DEFAULT_REFUNDABLE_FIAT =
            "TRANSACTION_REFUND_TYPE_IS_WALLET_AMOUNT_SHOULD_MORE_THAN_DEFAULT_REFUNDABLE_FIAT"
        const val TRANSACTION_REFUND_TYPE_IS_CASH_AMOUNT_SHOULD_UPTO_DEFAULT_REFUNDABLE_FIAT =
            "TRANSACTION_REFUND_TYPE_IS_CASH_AMOUNT_SHOULD_UPTO_DEFAULT_REFUNDABLE_FIAT"

        // general
        const val TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
        const val UNAUTHORIZED = "UNAUTHORIZED"
        const val USER_NOT_FOUND = "USER_NOT_FOUND"
        const val BAD_REQUEST = "BAD_REQUEST"
        const val INVALID_PAGINATION = "INVALID_PAGINATION"
        const val PARAMETERS_NOT_SPECIFIED = "PARAMETERS_NOT_SPECIFIED"
        const val SERVER_ERROR = "SERVER_ERROR"
        const val BITGO_SERVER_ERROR = "BITGO_SERVER_ERROR_OR_INVALID_DIGITAL_CURRENCY"

        // control panel
        const val USERS_ALREADY_IN_DATABASE = "USERS_ALREADY_IN_DATABASE"
        const val USERS_NOT_PRESENT = "USERS_NOT_PRESENT"

        // WebhhoksIO
        const val WEBHOOK_PROVIDER_ERROR = "WEBHOOK_PROVIDER_ERROR"
        const val WEBHOOK_PROVIDER_UNAVAILABLE = "WEBHOOK_PROVIDER_UNAVAILABLE"

        // expo notifications
        const val INVALID_EXPO_TOKEN = "INVALID_EXPO_TOKEN"
        const val NOTIFICATION_DATA_NOT_FOUND = "NOTIFICATION_DATA_NOT_FOUND"
        // onramp
        const val WRONG_WEBHOOK_ID = "WRONG_WEBHOOK_ID"
        const val INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE"
        const val TRANSACTION_ALREADY_FINALIZED = "TRANSACTION_ALREADY_FINALIZED"
        const val WRONG_AMOUNT = "WRONG_AMOUNT"
        const val TRANSACTION_HASH_NOT_SPECIFIED = "TRANSACTION_HASH_NOT_SPECIFIED"
        const val TRANSACTION_ALREADY_EXISTS = "TRANSACTION_ALREADY_EXISTS"
        const val NEGATIVE_AMOUNT_TRANSFER = "NEGATIVE_AMOUNT_TRANSFER"

        // contacts
        const val OWN_ACCOUNT_CONTACT = "OWN_ACCOUNT_CONTACT"
        const val CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND"
        const val NICKNAME_ALREADY_USED = "NICKNAME_ALREADY_USED"
        const val CONTACT_ALREADY_EXISTS = "CONTACT_ALREADY_EXISTS"

        // bitgo
        const val TRANSFER_NOT_FOUND = "TRANSFER_NOT_FOUND"
        const val EXTERNAL_SEND_INSIDE_THE_SYSTEM = "EXTERNAL_SEND_INSIDE_THE_SYSTEM"
        const val WALLET_NOT_AVAILABLE = "WALLET_NOT_AVAILABLE"
        const val UNKNOWN_WALLET_ERROR = "UNKNOWN_WALLET_ERROR"
        const val INVALID_WALLET_ADDRESS = "INVALID_WALLET_ADDRESS"
        const val WALLET_ADDRESS_NOT_EXIST = "WALLET_ADDRESS_NOT_EXIST"
        const val INSUFFICIENT_FUND = "INSUFFICIENT_FUND"
        const val INVALID_AMOUNT = "INVALID_AMOUNT"

        // merchant dashboard
        const val INVALID_ROLE = "INVALID_ROLE"
        const val INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND"
        const val CANNOT_DISABLE_OWN_ACCOUNT = "CANNOT_DISABLE_OWN_ACCOUNT"
        const val CANNOT_SEND_MERCHANT_TO_MERCHANT = "CANNOT_SEND_MERCHANT_TO_MERCHANT"

        // refund
        const val INVALID_REFUND_ERROR = "INVALID_REFUND"
        const val REFUND_ALREADY_EXISTS_ERROR = "REFUND_ALREADY_EXISTS_ERROR"
        const val NO_REFUND_REQUEST_FOUND_ERROR = "NO_REFUND_REQUEST_FOUND_ERROR"
        const val CANNOT_REFUND_MORE_THAN_RECEIVED_FIAT = "CANNOT_REFUND_MORE_THAN_RECEIVED_FIAT"
        const val ALREADY_FULLY_REFUNDED = "ALREADY_FULLY_REFUNDED"
        const val REFUND_NOT_FOUND = "REFUND_NOT_FOUND"

        // TODO: CBD Fake Ledger
        const val CANNOT_ALLOW_LESS_THEN_MIN_FIAT = "CANNOT_ALLOW_LESS_THEN_MIN_FIAT"
        const val CANNOT_ALLOW_LESS_THEN_MAX_FIAT = "CANNOT_ALLOW_MORE_THEN_MAX_FIAT"
        const val USER_BANK_ACCOUNT_NOT_FOUND = "USER_BANK_ACCOUNT_NOT_FOUND"
        const val BANK_ACCOUNT_ALREADY_ADDED = "BANK_ACCOUNT_ALREADY_ADDED"
        const val INVALID_BANK_ACCOUNT = "INVALID_BANK_ACCOUNT"
        const val DUPLICATE_BANK_ACCOUNT = "DUPLICATE_BANK_ACCOUNT"
        const val REFUND_AMOUNT_CANT_BE_GREATER_THAN_RECEIVED_AMOUNT = "REFUND_AMOUNT_CANT_BE_GREATER_THAN_RECEIVED_AMOUNT"
        const val REFUND_AMOUNT_CANT_BE_GREATER_THAN_BALANCE_AMOUNT = "REFUND_AMOUNT_CANT_BE_GREATER_THAN_BALANCE_AMOUNT"

        // TODO: Payment POC
        const val CURRENTLY_NOT_SUPPORTED_THIS_FIAT = "CURRENTLY_NOT_SUPPORTED_THIS_FIAT"
        const val TRANSACTION_INPROGRESS = "TRANSACTION_INPROGRESS"
        const val INSUFFICIENT_FUNDS_VEPAY = "INSUFFICIENT_FUNDS_VEPAY"

        // TODO: Issuance Dashboard
        const val ISSUANCE_BANK_NOT_FOUND = "ISSUANCE_BANK_NOT_FOUND"
        const val TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND"
        const val ALREADY_INVITATION_SEND = "ALREADY_INVITATION_SEND"
        const val WALLET_DISABLED = "WALLET_DISABLED"
        const val WALLET_DISABLED_RECIPIENT = "WALLET_DISABLED_RECIPIENT"
        const val P2P_TRANSFER_DISABLED = "P2P_TRANSFER_DISABLED"
        const val ISSUANCE_WALLET_USER_ALREDY_MAPPED = "ISSUANCE_WALLET_USER_ALREADY_MAPPED"
        const val UNSUPPORTED_TOKEN = "UNSUPPORTED_TOKEN"
        const val OTHER_BANK_TRANSFER_NOT_ALLOWED = "OTHER_BANK_TRANSFER_NOT_ALLOWED"

        // TODO: Transaction Wallet Config
        const val CONVERSION_RATE_NOT_FOUND = "CONVERSION_RATE_NOT_FOUND"
        const val CONVERSION_RATE_ALREADY_ADDED = "CONVERSION_RATE_ALREADY_ADDED"
        const val CONVERSION_RATE_ADJUSTMENT_ALREADY_ADDED = "CONVERSION_RATE_ADJUSTMENT_ALREADY_ADDED"
        const val TRANSACTION_TYPE_NOT_FOUND = "TRANSACTION_TYPE_NOT_FOUND"
        const val WALLET_FEE_NOT_FOUND = "WALLET_FEE_NOT_FOUND"
        const val WALLET_FEE_CONFIG_NOT_FOUND = "WALLET_FEE_CONFIG_NOT_FOUND"
        const val WALLET_FEE_CONFIG_ALREADY_ADDED = "WALLET_FEE_CONFIG_ALREADY_ADDED"
        const val TRANSACTION_LIMIT_CONFIG_NOT_FOUND = "TRANSACTION_LIMIT_CONFIG_NOT_FOUND"
        const val TRANSACTION_LIMIT_ALREADY_ADDED = "TRANSACTION_LIMIT_ALREADY_ADDED"
        const val LANGUAGE_ALREADY_ADDED = "LANGUAGE_ALREADY_ADDED"
        const val LANGUAGE_MAPPED_WITH_INSTITUTIONS = "LANGUAGE_MAPPED_WITH_INSTITUTIONS"
        const val LANGUAGE_NOT_FOUND = "LANGUAGE_NOT_FOUND"
        const val COUNTRY_NOT_FOUND = "COUNTRY_NOT_FOUND"
        const val CANNOT_ALLOW_LESS_THEN_MIN_VALUE = "CANNOT_ALLOW_LESS_THEN_MIN_VALUE"
        const val CANNOT_ALLOW_MORE_THEN_MAX_VALUE = "CANNOT_ALLOW_MORE_THEN_MAX_VALUE"
        const val TRANSACTION_COUNT_EXCEEDED = "TRANSACTION_COUNT_EXCEEDED"
        const val INVALID_QR = "INVALID_QR"
        const val SENDER_RECEIVER_WALLET_ADDRESS_CANT_BE_SAME = "SENDER_RECEIVER_WALLET_ADDRESS_CANT_BE_SAME"
        const val SENDER_RECEIVER_INSTITUTION_SHOULD_BE_SAME = "SENDER_RECEIVER_INSTITUTION_SHOULD_BE_SAME"
        const val BLOCKCHAIN_SERVICE_NOT_FOUND = "BLOCKCHAIN_SERVICE_NOT_FOUND"

        const val INVALID_ENCRYPTED_PASSCODE = "INVALID_PASSCODE"
        const val SALT_KEY_NOT_FOUND = "SALT_KEY_NOT_FOUND"
        const val PASSCODE_NOT_FOUND = "PASSCODE_NOT_FOUND"
        const val PASSCODE_SET_SUCCESSFULLY = "You have successfully set your passcode."
        const val PASSCODE_UPDATED_SUCCESSFULLY = "You have successfully changed your passcode."
        const val PASSCODE_NOT_MATCH = "PASSCODE_DID_NOT_MATCH"
        const val PASSCODE_HASH_ALREADY_USED = "PASSCODE_HASH_ALREADY_USED"
        const val BLOCKCHAIN_INSUFFICIENT_AMOUNT = "BLOCKCHAIN_INSUFFICIENT_AMOUNT"
        const val INVALID_WALLET_ADDRESS_MANDATE = "WALLET_ADDRESS_IS_MANDATORY"
        const val INVALID_EMAIL_WALLET_ADDRESS_MATCH = "EMAIL_ID_AND_WALLET_ADDRESS_ARE_NOT_MATCHING"
        const val INVALID_AGGREGATOR_PREFERENCE_ID = "INVALID_AGGREGATOR_PREFERENCE_ID"
        const val INVALID_INSTITUTION_ID = "INVALID_INSTITUTION_ID"
        const val INVALID_MERCHANT_GROUP_ID = "INVALID_MERCHANT_GROUP_ID"
        const val INVALID_MERCHANT_ID = "INVALID_MERCHANT_ID"

        const val INVALID_ID = "INVALID_ID"

        // TODO: Customer Offline Transaction Limit Error Code
        const val YEARLY_LIMIT_EXHAUSTED = "YEARLY_LIMIT_EXHAUSTED"
        const val HALF_YEARLY_LIMIT_EXHAUSTED = "HALF_YEARLY_LIMIT_EXHAUSTED"
        const val QUARTERLY_LIMIT_EXHAUSTED = "QUARTERLY_LIMIT_EXHAUSTED"
        const val MONTHLY_LIMIT_EXHAUSTED = "MONTHLY_LIMIT_EXHAUSTED"
        const val WEEKLY_LIMIT_EXHAUSTED = "WEEKLY_LIMIT_EXHAUSTED"
        const val DAILY_LIMIT_EXHAUSTED = "DAILY_LIMIT_EXHAUSTED"
        const val RECIPIENT_WALLET_NOT_ACTIVATED = "RECIPIENT_WALLET_NOT_ACTIVATED"

        const val CUSTOMER_WALLET_REQUIRED = "CUSTOMER_WALLET_REQUIRED"
        const val RECIPIENT_WALLET_REQUIRED = "RECIPIENT_WALLET_REQUIRED"
        const val SENDER_WALLET_INSUFFICIENT_FUNDS = "SENDER_WALLET_INSUFFICIENT_FUNDS"
        const val ISSUER_WALLET_INSUFFICIENT_FUNDS = "ISSUER_WALLET_INSUFFICIENT_FUNDS"
        const val TOKEN_NAME_ALREADY_AVAILABLE = "TOKEN_NAME_ALREADY_AVAILABLE"
        const val ASSET_QUANTITY_ALREADY_EXIST = "ASSET_QUANTITY_ALREADY_EXIST"
        const val FROM_DATE_REQUIRED = "FROM_DATE_REQUIRED"
        const val INVALID_CUSTOMER_ID = "INVALID_CUSTOMER_ID"
        const val CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"

        const val NO_OPTIN_ACCOUNT_CREATION_ERROR = "NO_OPTIN_ACCOUNT_CREATION_ERROR"
        const val WRONG_INPUT = "WRONG_INPUT"
        const val WRONG_PASSWORD = "WRONG_PASSWORD"
        const val USER_LOCKED = "USER_LOCKED"
        const val EXPIRED_OR_ALREADY_USED = "EXPIRED_OR_ALREADY_USED"
        const val OTP_NOT_MATCH = "OTP_NOT_MATCH"
    }
}
