create table order_webhook_log (
    id bigint generated by default as identity not null,
    webhook_id bigint not null,
    order_id bigint not null,
    response_status varchar(255),
    retry_count int,
    timestamp timestamp,
    primary key (id),
    constraint fk_webhook foreign key(webhook_id) references order_webhook(id),
    constraint fk_order foreign key(order_id) references wadzpay_order(id)
);

alter table order_webhook drop column input_id;
alter table order_webhook drop column trigger_url;
