CREATE TABLE IF NOT EXISTS pos_inwards_log
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wallet VARCHAR(255),
    address VARCHAR(255),
    value VARCHAR(255),
    asset_crypto VARCHAR(255),
    type VARCHAR(255),
    block_id VARCHAR(255),
    entries VARCHAR,
    bitgo_id VARCHAR,
bitgo_coin VARCHAR,
bitgo_type VARCHAR,
bitgo_fee VARCHAR,
bitgo_base_value VARCHAR,
    created_at timestamp);
