CREATE TABLE IF NOT EXISTS wadzpay_refund_transactions_finance
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id bigint
        constraint fk7oppkh2rjl9i0h48ondcmj00e
            references account_owner,
    pos_id VARCHAR(255),
    uuid VARCHAR(255),
    transaction_id bigint constraint fkaslhlskjfpekodf references transaction(id),
    asset_crypto VARCHAR(255),
    address  VARCHAR(255),
    amount_crypto numeric(40,20),
    fee_by_wadzpay numeric(40,20),
    fee_by_blockchain numeric(40,20),
    type VARCHAR(255),
    blockchain_hash VARCHAR(255),
    description VARCHAR(255),
    created_at timestamp
);
