-- Create institution_role_master;
create table if not exists institution_role_master
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR NOT NULL,
    created_date timestamp NULL,
    created_by BIGINT NULL,
    modified_date timestamp NULL,
    modified_by BIGINT NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_institution_role_master PRIMARY KEY (id)
    );

-- Create institution_user_management;

create table if not exists institution_user_management
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    first_name VARCHAR NULL,
    middle_name VARCHAR NULL,
    last_name VARCHAR NULL,
    phone_number  VARCHAR NULL,
    email  VARCHAR NULL,
    department VARCHAR NULL,
    role_id  BIGINT NOT NULL,
    created_date timestamp NULL,
    created_by BIGINT NULL,
    modified_date timestamp NULL,
    modified_by BIGINT NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_institution_user_management PRIMARY KEY (id),
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id),
    CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES institution_role_master (id)
    );

-- Create institution_management_field_config;

create table if not exists institution_management_field_config
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    field_name_key VARCHAR NULL,
    is_mandatory BOOLEAN NULL,
    is_allow_show BOOLEAN NULL,
    is_allow_edit BOOLEAN NULL,
    created_date timestamp NULL,
    created_by BIGINT NULL,
    modified_date timestamp NULL,
    modified_by BIGINT NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_institution_management_field_config PRIMARY KEY (id),
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id)
    );



-- update institution_role_master;

INSERT INTO institution_role_master (role_name,is_active)
VALUES ('Admin',true);

-- Alter Table institution_user_management

ALTER TABLE institution_user_management
    ADD COLUMN IF NOT EXISTS cognito_username VARCHAR NULL;