CREATE TABLE IF NOT EXISTS apis_log
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    end_point            VARCHAR                                 NOT NULL,
    mesg VARCHAR                                ,
    user_email VARCHAR,
    other VARCHAR ,
    created_at timestamp
);
