
-- Alter  language_master table and primary key constraint;
ALTER TABLE language_master ADD CONSTRAINT pk_language_master PRIMARY KEY (id);

-- A new table for country language_issuance_mapping;
create table if not exists language_issuance_mapping
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    language_id BIGINT NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    created_date timestamp NULL,
    created_by BIGINT NULL,
    modified_date timestamp NULL,
    modified_by BIGINT NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_language_issuance_mapping PRIMARY KEY (id),
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id),
    CONSTRAINT fk_language_id FOREIGN KEY (language_id) REFERENCES language_master (id),
    CONSTRAINT fk_modified_by FOREIGN KEY (modified_by) REFERENCES issuance_banks (id),
    CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES issuance_banks (id)
);

-- Alter  newly created table and makes owner to postgres;
alter table language_issuance_mapping owner to postgres;
