CREATE TABLE unmatched_transaction
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount VARCHAR(255),
    asset VARCHAR,
    created_at TIMESTAMP,
    blockchain_tx_id VARCHAR NOT NULL,
    matched_with_id BIGINT,
    CONSTRAINT pk_unmatched_transaction PRIMARY KEY (id)
);

ALTER TABLE unmatched_transaction
    ADD CONSTRAINT FK_UNMATCHED_TRANSACTION_ON_MATCHED_WITH FOREIGN KEY (matched_with_id) REFERENCES transaction (id);
