create table if not exists user_details
(
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483645 CACHE 1 ),
    name     character varying(255),
    user_preference_id     character varying(255)  NOT NULL UNIQUE,
    country_code     character varying(3) NULL,
    mobile_no     character varying(12)  NULL UNIQUE,
    email_id     character varying(255)  NOT NULL UNIQUE,
    designation     character varying(255),
    department_id     int,
    role_id     int,
    comment     character varying(1500),
    status     character varying(255),
    last_success_login    timestamp NULL,
    password     character varying(255),
    failed_attempts    int  DEFAULT 0,
    created_at    timestamp NULL,
    created_by    bigint NULL,
    updated_at    timestamp NULL,
    updated_by    bigint NULL,
    constraint pkey_user_details primary key (user_id),
    CONSTRAINT fk_department_id FOREIGN KEY (department_id) REFERENCES department (department_id),
    CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES role (role_id),
    CONSTRAINT fk_user_details_created_by FOREIGN KEY (created_by) REFERENCES user_details (user_id),
    CONSTRAINT fk_user_details_updated_by FOREIGN KEY (updated_by) REFERENCES user_details (user_id)
    );

create table if not exists user_details_transaction
(
    user_details_transaction_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2094967295 CACHE 1 ),
    user_id bigint,
    name     character varying(255),
    user_preference_id     character varying(255),
    country_code     character varying(3),
    mobile_no     character varying(12),
    email_id     character varying(255),
    designation     character varying(255),
    department_id     int,
    role_id     int,
    comment     character varying(1500),
    status     character varying(255),
    last_success_login    timestamp NULL,
    password     character varying(255),
    failed_attempts    int DEFAULT 0,
    created_updated_at timestamp NULL,
    created_updated_by  bigint NULL,
    constraint pkey_user_details_transaction primary key (user_details_transaction_id),
    CONSTRAINT fk_department_id FOREIGN KEY (department_id) REFERENCES department (department_id),
    CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES role (role_id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES user_details (user_id),
    CONSTRAINT fk_user_created_updated_by FOREIGN KEY (created_updated_by) REFERENCES user_details (user_id)
    );

create table if not exists level_user_details_mapping
(
    level_user_details_mapping_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2094967295 CACHE 1 ),
    level_id smallint NOT NULL,
    user_id bigint NOT NULL,
    created_at    timestamp NULL,
    created_by    bigint NULL,
    constraint pkey_level_user_details_mapping primary key (level_user_details_mapping_id),
    CONSTRAINT fk_level_id FOREIGN KEY (level_id) REFERENCES levels (level_id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES user_details (user_id),
    CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES user_details (user_id)
    );
