create table if not exists kyc_logs
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    call_back_type VARCHAR,
    callback_date   VARCHAR,
    client_ip  VARCHAR,
    customer_id  VARCHAR,
    first_attempt_date  VARCHAR, id_first_name VARCHAR,id_dob VARCHAR,id_country VARCHAR,id_last_name VARCHAR, id_number VARCHAR,id_scan_image VARCHAR,id_scan_image_backside VARCHAR,
    id_scan_image_face VARCHAR,id_scan_source VARCHAR,id_scan_status VARCHAR,id_subtype VARCHAR,identity_verification VARCHAR,jumio_id_scan_reference VARCHAR,merchant_id_scan_reference VARCHAR,
    personal_number VARCHAR,transaction_date VARCHAR,verification_status VARCHAR,user_account_id BIGINT,
    CONSTRAINT pk_kyc_logs PRIMARY KEY (id),
    CONSTRAINT FK_CONTACT_ON_USERACCOUNT FOREIGN KEY (user_account_id) REFERENCES user_account (id)
);

ALTER TABLE user_account
    ADD IF NOT EXISTS kyc_verified VARCHAR

