create table if not exists wadzpay_minter
(
    wadzpay_minter_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asset_name VARCHAR NOT NULL,
    asset_mint_amount numeric(40, 20) NOT NULL,
    asset_mint_base_unit VARCHAR(255),
    asset_url VARCHAR(255),
    wadzpay_minter_address VARCHAR(255) NOT NULL,
    constraint wadzpay_minter_pkey primary key(wadzpay_minter_id)
);

