CREATE TABLE IF NOT EXISTS fiat_sub_account
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_reference VARCHAR                                 NOT NULL UNIQUE,
    user_account_id   BIGINT                                 NOT NULL,
    fiatAsset      VARCHAR,
    balance        numeric(40, 20) default 0.0,
    updated_at     timestamp
);
