-- A new table for country master;
create table if not exists country
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_code VARCHAR NOT NULL,
    country_name VARCHAR NOT NULL,
    country_image_url  VARCHAR NULL,
    created_date timestamp NULL,
    modified_date timestamp NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_country PRIMARY KEY (id)
);

-- Alter  newly created table and makes owner to postgres;
alter table country owner to postgres;

-- Alter  newly created table and makes owner to postgres;
ALTER TABLE country ADD CONSTRAINT constraint_name UNIQUE (country_name);
