-- A new table for Audit logs;
create table if not exists issuance_banks_audit_logs
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    column_name  VARCHAR NULL,
    old_value VARCHAR NULL,
    new_value VARCHAR NULL,
    is_active BOOLEAN DEFAULT true,
    modified_date timestamp NULL,
    modified_by BIGINT NULL,
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id),
    CONSTRAINT fk_modified_by FOREIGN KEY (modified_by) REFERENCES issuance_banks (id)
);

-- Alter  newly created table and makes owner to postgres;
alter table issuance_banks_audit_logs owner to postgres;
