create table if not exists issuance_banks
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bank_name VARCHAR NOT NULL,
    country_code   VARCHAR NOT NULL,
    time_zone  VARCHAR NOT NULL,
    default_currency  VARCHAR NOT NULL,
    phone_number  VARCHAR NULL,
    email  VARCHAR NULL,
    cognito_username VARCHAR NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_issuance_banks PRIMARY KEY (id)

    );
