create table if not exists asset_creation_request
(
    asset_creation_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asset_name VARCHAR NOT NULL,
    asset_unit VARCHAR NOT NULL,
    asset_amount BIGINT NOT NULL,
    decimal_places VARCHAR,
    requester_id BIGINT NOT NULL,
    request_state VARCHAR,
    request_date timestamp,
    completed_state VARCHAR,
    date_of_provision timestamp,
    provision_account VARCHAR,
    provision_user_id BIGINT ,
    provisioned_token_id VARCHAR,
    constraint asset_creation_request_pkey primary key(asset_creation_request_id)
    );

ALTER TABLE asset_creation_request
    ADD CONSTRAINT FK_requester_id FOREIGN KEY (requester_id) REFERENCES user_account (id);

ALTER TABLE asset_creation_request
    ADD CONSTRAINT FK_provision_user_id FOREIGN KEY (provision_user_id) REFERENCES user_account (id);
