CREATE TABLE IF NOT EXISTS request_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    host_name_server VARCHAR,
    canonical_host_name_server VARCHAR,
    host_address_server VARCHAR,
    request_status VARCHAR,
    request_local_addr VARCHAR,
    request_local_name VARCHAR,
    request_locale VARCHAR,
    request_local_port VARCHAR,
    request_method VARCHAR,
    request_auth VARCHAR,
    request_uri VARCHAR,
    user_remote_addr VARCHAR,
    request_parameter_map VARCHAR,
    response_Sent VARCHAR,
    created_at TIMESTAMP
);
