create table if not exists issuance_wallet_fee_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wallet_fee_id  VARCHAR NOT NULL,
    fee_type  VARCHAR NOT NULL,
    created_at timestamp NOT NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_issuance_wallet_fee PRIMARY KEY (id)
    );

create table if not exists issuance_wallet_config
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    currency  VARCHAR NOT NULL,
    wallet_fee_id  VARCHAR NOT NULL,
    frequency  VARCHAR NULL,
    value  VARCHAR  NULL,
    min_value numeric(20, 2),
    max_value numeric(20, 2),
    user_category  VARCHAR NULL,
    created_date timestamp NULL,
    is_active BOOLEAN DEFAULT true,
    created_by BIGINT NOT NULL,
    modified_date timestamp NULL,
    modified_by BIGINT NULL,
    CONSTRAINT pk_issuance_wallet_config PRIMARY KEY (id),
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id),
    CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES issuance_banks (id)
    );


-- update issuance_wallet_fee_type;

INSERT INTO issuance_wallet_fee_type (wallet_fee_id,
                                      fee_type,
                                      created_at,
                                      is_active)
VALUES ('WF_001', 'Activation Fee', '2023-03-20 10:31:49.735000',true),
       ('WF_002', 'Loading Fee', '2023-03-20 10:31:49.735000',true),
       ('WF_003', 'Service Fee', '2023-03-20 10:31:49.735000',true),
       ('WF_004', 'Unspent Digital Currency Refund Fee', '2023-03-20 10:31:49.735000',true),
       ('WF_005', 'Wallet Balance', '2023-03-20 10:31:49.735000',true);
