-- Alter user_details table;
ALTER TABLE public.user_details
DROP COLUMN comment;

ALTER TABLE public.user_details
    ADD COLUMN if not exists password_uuid character varying(36) null,
    ADD COLUMN if not exists otp character varying(36) null,
    ADD COLUMN if not exists otp_valid_till  timestamp NULL;

-- Alter user_details_transaction table;
ALTER TABLE public.user_details_transaction
    ADD COLUMN if not exists password_uuid character varying(36) null,
    ADD COLUMN if not exists otp character varying(36) null,
    ADD COLUMN if not exists otp_valid_till  timestamp NULL;

-- create table user login config ;
create table if not exists user_login_config
(
    user_login_config_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483645 CACHE 1 ),
    aggregator_id bigint NOT NULL,
    no_of_failed_login_attempts smallint null,
    otp_valid_time_in_seconds smallint null,
    otp_length smallint null,
    resend_otp_link_in_seconds smallint null,
    resend_otp_no_of_times smallint null,
    send_otp_via character varying(10) null,
    is_multifactor_enable boolean,
    created_at    timestamp NULL,
    created_by    bigint,
    updated_at    timestamp NULL,
    updated_by    bigint,
    status        boolean,
    constraint pkey_user_login_config_id primary key (user_login_config_id),
    CONSTRAINT fk_user_login_config_id_created_by FOREIGN KEY (created_by) REFERENCES user_details (user_id),
    CONSTRAINT fk_user_login_config_id_updated_by FOREIGN KEY (updated_by) REFERENCES user_details (user_id)
    );


-- create table user login config transaction;
create table if not exists user_login_config_transaction
(
    user_login_config_transaction_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483645 CACHE 1 ),
    user_login_config_id bigint NOT NULL,
    aggregator_id bigint NOT NULL,
    no_of_failed_login_attempts smallint null,
    otp_valid_time_in_seconds smallint null,
    otp_length smallint null,
    resend_otp_link_in_seconds smallint null,
    resend_otp_no_of_times smallint null,
    send_otp_via character varying(10) null,
    is_multifactor_enable boolean,
    created_updated_at timestamp NULL,
    created_updated_by bigint,
    status boolean,
    constraint pkey_user_login_config_transaction_id primary key (user_login_config_transaction_id),
    CONSTRAINT fk_user_login_config_id_created_updated_by FOREIGN KEY (created_updated_by) REFERENCES user_details (user_id)
    );

-- create table user login nacl;
create table if not exists nacl
(
    nacl_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483645 CACHE 1 ),
    user_id bigint NOT NULL,
    nacl_key varchar null,
    created_at    timestamp NULL,
    created_by    bigint,
    updated_at    timestamp NULL,
    updated_by    bigint,
    status        boolean,
    constraint pkey_nacl_id primary key (nacl_id),
    CONSTRAINT fk_nacl_user_id FOREIGN KEY (user_id) REFERENCES user_details (user_id),
    CONSTRAINT fk_nacl_created_by FOREIGN KEY (created_by) REFERENCES user_details (user_id),
    CONSTRAINT fk_nacl_updated_by FOREIGN KEY (updated_by) REFERENCES user_details (user_id)
    );
