drop table institution CASCADE;

create table if not exists institution
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institution_id VARCHAR(255),
    aggregator_preference_id  VARCHAR(255),
    insitution_preference_id VARCHAR(255),
    insitution_name VARCHAR(255),
    insitution_status VARCHAR(255),
    address_id BIGINT,
    admin_details_id BIGINT,
    bank_details_id BIGINT,
    contact_details_id BIGINT,
    info_id BIGINT,
    others_id BIGINT,
    constraint institution_pkey primary key (id),
    constraint fk_instition_aggregator_id foreign key(aggregator_preference_id) references aggregator(aggregator_preference_id)
    );


ALTER TABLE institution
    ADD CONSTRAINT unique_columns_constraint1 UNIQUE (aggregator_preference_id, institution_id);

