create table if not exists user_comments
(
    user_comment_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483645 CACHE 1 ),
    user_id     bigint NOT NULL,
    comment     character varying(1500),
    created_at    timestamp NULL,
    created_by    bigint NULL,
    constraint pkey_user_comments primary key (user_comment_id),
    CONSTRAINT fk_user_details_created_by FOREIGN KEY (created_by) REFERENCES user_details (user_id),
    CONSTRAINT fk_user_details_user_id FOREIGN KEY (user_id) REFERENCES user_details (user_id)
    );
