drop table merchant_acquirer CASCADE;
create table if not exists merchant_acquirer
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    merchant_acquirer_id VARCHAR(255),
    aggregator_preference_id  VARCHAR(255),
    insitution_preference_id  VARCHAR(255),
    merchant_group_preference_id VARCHAR(255),
    merchant_acquirer_name VARCHAR(255),
    merchant_acquirer_status VARCHAR(255),
    address_id BIGINT,
    admin_details_id BIGINT,
    bank_details_id BIGINT,
    contact_details_id BIGINT,
    info_id BIGINT,
    others_id BIGINT,
    constraint merchant_acquirer_pkey primary key (id),
    constraint fk_merchant_aquirer_aggregator_pref_id foreign key(aggregator_preference_id) references aggregator(aggregator_preference_id)
    );
