-- Table: public.levels

-- DROP TABLE IF EXISTS public.levels;

CREATE TABLE IF NOT EXISTS public.levels
(
    level_id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32766 CACHE 1 ),
    level_name character varying(25) COLLATE pg_catalog."default",
    image_url character varying(255) COLLATE pg_catalog."default",
    level_number smallint,
    created_at timestamp without time zone,
    created_by bigint,
    updated_at timestamp without time zone,
    updated_by bigint,
    status boolean,
    CONSTRAINT levels_pkey PRIMARY KEY (level_id),
    CONSTRAINT levels_name_uk UNIQUE (level_name),
    CONSTRAINT fk_levels_created_by FOREIGN KEY (created_by)
    REFERENCES public.user_account (id) MATCH SIMPLE
                         ON UPDATE NO ACTION
                         ON DELETE NO ACTION,
    CONSTRAINT fk_levels_updated_by FOREIGN KEY (updated_by)
    REFERENCES public.user_account (id) MATCH SIMPLE
                         ON UPDATE NO ACTION
                         ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.levels
    OWNER to postgres;
-- transaction table
-- Table: public.levels_transaction

-- DROP TABLE IF EXISTS public.levels_transaction;

CREATE TABLE IF NOT EXISTS public.levels_transaction
(
    level_transaction_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    level_id smallint,
    level_name character varying(25) COLLATE pg_catalog."default",
    image_url character varying(255) COLLATE pg_catalog."default",
    level_number smallint,
    created_updated_at timestamp without time zone,
    created_updated_by bigint,
    status boolean,
    CONSTRAINT levels_transaction_pkey PRIMARY KEY (level_transaction_id),
    CONSTRAINT fk_levels_transaction_created_updated_by FOREIGN KEY (created_updated_by)
    REFERENCES public.user_account (id) MATCH SIMPLE
                                 ON UPDATE NO ACTION
                                 ON DELETE NO ACTION
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.levels_transaction
    OWNER to postgres;
