create table if not exists issuance_banks_user_entry
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    user_account_id   BIGINT NOT NULL,
    valid_from_date timestamp NULL,
    valid_to_date timestamp NULL,
    status VARCHAR NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_issuance_banks_user PRIMARY KEY (id),
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id),
    CONSTRAINT fk_usere_account_id FOREIGN KEY (user_account_id) REFERENCES user_account (id)
);
