create table if not exists wadzpay_algo_addresses
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 algoaddress varchar(255) constraint uk_algoaddress unique,
algomnu varchar(255) not null,
CONSTRAINT pk_wadzpay_algo_addresses PRIMARY KEY (id)
);

alter table wadzpay_algo_addresses owner to postgres;
