CREATE TABLE IF NOT EXISTS user_bank_account
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bank_account_number            VARCHAR         NOT NULL,
    account_holder_name            VARCHAR         NULL,
    ifsc_code			     VARCHAR 	    NULL,
    branch_name 			     VARCHAR 	   NULL,
    user_account_id 		     BIGINT          NOT NULL,
    CONSTRAINT pk_userbankaccount PRIMARY KEY (id),
    updated_at     timestamp
    );

ALTER TABLE user_bank_account
    ADD CONSTRAINT FK_USERBANKACCOUNT_ON_USER_ACCOUNT FOREIGN KEY (user_account_id) REFERENCES user_account (id);
