
create table if not exists modules
(
    module_id   smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32766 CACHE 1 ),
    module_name character varying(50),
    module_type character varying(20),
    module_url  character varying(255),
    image_url  character varying(255),
    parent_id   smallint,
    sorting     numeric(3, 2),
    created_at  timestamp NULL,
    created_by  bigint,
    updated_at  timestamp NULL,
    updated_by  bigint,
    status      boolean,
    constraint modules_pkey primary key (module_id),
    CONSTRAINT fk_modules_created_by FOREIGN KEY (created_by) REFERENCES user_account (id),
    CONSTRAINT fk_modules_updated_by FOREIGN KEY (updated_by) REFERENCES user_account (id)

);
create table if not exists modules_transaction
(
    module_transaction_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    module_id             smallint,
    module_name           character varying(50),
    module_type           character varying(20),
    module_url            character varying(255),
    image_url            character varying(255),
    parent_id             smallint,
    sorting               numeric(3, 2),
    created_updated_at    timestamp NULL,
    created_updated_by    bigint,
    status                boolean,
    constraint modules_transaction_pkey primary key (module_transaction_id),
    CONSTRAINT fk_modules_transaction_created_updated_by FOREIGN KEY (created_updated_by) REFERENCES user_account (id)
);



