drop table sub_merchant_acquirer CASCADE;
create table if not exists sub_merchant_acquirer
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregator_preference_id  VARCHAR(255),
    insitution_preference_id  VARCHAR(255),
    merchant_group_preference_id VARCHAR(255),
    merchant_acquirer_preference_id VARCHAR(255),
    sub_merchant_acquirer_id VARCHAR(255),
    sub_merchant_acquirer_name VARCHAR(255),
    sub_merchant_acquirer_status VARCHAR(255),
    address_id BIGINT,
    admin_details_id BIGINT,
    bank_details_id BIGINT,
    contact_details_id BIGINT,
    info_id BIGINT,
    others_id BIGINT,
    constraint sub_merchant_acquirer_pkey primary key (id),
    constraint fk_sub_merchant_aquirer_mrchnt_grp_pref_id foreign key(aggregator_preference_id,insitution_preference_id,merchant_group_preference_id,merchant_acquirer_preference_id) references merchant_acquirer(aggregator_preference_id, insitution_preference_id,merchant_group_preference_id,merchant_acquirer_id)
    );


ALTER TABLE sub_merchant_acquirer
    ADD CONSTRAINT unique_columns_sub_merchant_acquirer UNIQUE (aggregator_preference_id,insitution_preference_id,merchant_group_preference_id,merchant_acquirer_preference_id,sub_merchant_acquirer_id);


ALTER TABLE sub_merchant_acquirer
DROP CONSTRAINT fk_sub_merchant_aquirer_mrchnt_grp_pref_id,
    ADD CONSTRAINT fk_sub_merchant_aquirer_mrchnt_grp_pref_id
        FOREIGN KEY (aggregator_preference_id, insitution_preference_id,merchant_group_preference_id,merchant_acquirer_preference_id)
            REFERENCES merchant_acquirer (aggregator_preference_id,insitution_preference_id,merchant_group_preference_id,merchant_acquirer_id)
            ON DELETE CASCADE;

ALTER TABLE sub_merchant_acquirer
    ADD COLUMN sub_merchant_acquirer_logo VARCHAR(1500);

