CREATE TABLE IF NOT EXISTS transaction_wallet_fee_details
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, --P.K --nextval('transaction_wallet_fee_details'::regclass),
    transaction_uuid varchar NULL,
    user_account_id BIGINT NOT NULL, --F.K. from USER_ACCOUNT table
    wallet_fee_id BIGINT NOT NULL, --F.K. from ISSUANCE_WALLET_FEE table
    base_amount numeric(40,20) DEFAULT 0.0,
    fee_amount numeric(40,20) DEFAULT 0.0,
    fee_name varchar null,
    fee_type varchar null,
    fee_value numeric(40,20) DEFAULT 0.0,
    fee_frequency varchar null,
    created_at timestamp default(now()),
    last_updated_on timestamp,
    CONSTRAINT transaction_wallet_fee_details_pkey PRIMARY KEY (id),
    CONSTRAINT fk_user_account_id FOREIGN KEY (user_account_id) REFERENCES user_account (id)
    );