CREATE TABLE IF NOT EXISTS conversion_markup
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    digital_currency   VARCHAR(255),
    mark_up            int,
    mark_up_percentage numeric(4, 2),
    from_date          TIMESTAMP,
    to_date            TIMESTAMP,
    CONSTRAINT digital_currency PRIMARY KEY (id)
);

-- update conversion_markup set digital_currency = 'WTK' where id!=0;

INSERT INTO conversion_markup (digital_currency,
                               mark_up,
                               mark_up_percentage,
                               from_date,
                               to_date)
VALUES ('WTK', 1, 0.01,'2022-08-08 10:31:49.735000','2022-08-08 10:31:49.735000'),
       ('USDT', 1, 0.01,'2022-08-08 10:31:49.735000','2022-08-08 10:31:49.735000'),
       ('ETH', 2, 0.02,'2022-08-08 10:31:49.735000','2022-08-08 10:31:49.735000'),
       ('BTC', 1, 0.01,'2022-08-08 10:31:49.735000','2022-08-08 10:31:49.735000'),
       ('USDC', 1, 0.01,'2022-08-08 10:31:49.735000','2022-08-08 10:31:49.735000');
