ALTER TABLE issuance_banks
    ADD IF NOT EXISTS institution_id VARCHAR NULL,
    ADD IF NOT EXISTS institution_abbreviation VARCHAR NULL,
    ADD IF NOT EXISTS institution_description TEXT,
    ADD IF NOT EXISTS institution_region VARCHAR NULL,
    ADD IF NOT EXISTS destination_currency  VARCHAR(50),
    ADD IF NOT EXISTS company_type  VARCHAR NULL,
    ADD IF NOT EXISTS industry_type  VARCHAR NULL,
    ADD IF NOT EXISTS activation_date  timestamp NULL,
    ADD IF NOT EXISTS address_line1 TEXT,
    ADD IF NOT EXISTS address_line2 TEXT,
    ADD IF NOT EXISTS address_line3 TEXT,
    ADD IF NOT EXISTS city VARCHAR NULL,
    ADD IF NOT EXISTS provice VARCHAR NULL,
    ADD IF NOT EXISTS country VARCHAR NULL,
    ADD IF NOT EXISTS postal_code VARCHAR NULL,
    ADD IF NOT EXISTS primary_contact_first_name VARCHAR NULL,
    ADD IF NOT EXISTS primary_contact_middle_name VARCHAR NULL,
    ADD IF NOT EXISTS primary_contact_last_name VARCHAR NULL,
    ADD IF NOT EXISTS primary_contact_email_id VARCHAR NULL,
    ADD IF NOT EXISTS primary_contact_phone_number VARCHAR NULL,
    ADD IF NOT EXISTS primary_contact_designation VARCHAR NULL,
    ADD IF NOT EXISTS primary_contact_department VARCHAR NULL,
    ADD IF NOT EXISTS customer_offline_transaction BOOLEAN  NULL,
    ADD IF NOT EXISTS merchant_offline_transaction BOOLEAN NULL,
    ADD IF NOT EXISTS institution_status BOOLEAN  NULL,
    ADD IF NOT EXISTS approval_work_flow BOOLEAN  NULL,
    ADD IF NOT EXISTS p2p_transfer BOOLEAN  NULL,
    ALTER COLUMN bank_name DROP NOT NULL,
    ALTER COLUMN country_code DROP NOT NULL,
    ALTER COLUMN time_zone DROP NOT NULL,
    ALTER COLUMN default_currency DROP NOT NULL;