CREATE TABLE IF NOT EXISTS transaction_pos
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    merchantId VARCHAR(255),
    posId VARCHAR(255),
    uuid VARCHAR(255),
    assetCrypto VARCHAR(255),
    assetFiat VARCHAR(255),
    address  VARCHAR(255),
    amountFiat VARCHAR(255),
    amountCrypto VARCHAR(255),
    feeWadzPay VARCHAR(255),
    feeExternal VARCHAR(255),
    type VARCHAR(255),
    senderId VARCHAR(255),
    blockChainId VARCHAR(255),
    description VARCHAR(255),
    status VARCHAR(255),
    created_at timestamp,
    saltKey BIGINT,
    CONSTRAINT pk_transactionpos PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS pos_salt
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    saltKey    VARCHAR(255),
    tx_id BIGINT,
    CONSTRAINT pk_possalt PRIMARY KEY (id),
    FOREIGN KEY (tx_id) REFERENCES transaction_pos(id)
);


ALTER TABLE transaction_pos
    ADD CONSTRAINT fk_transaction_pos FOREIGN KEY (saltKey) REFERENCES pos_salt (id);




