-- A new table for language master;
create table if not exists language_master
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    language_uuid UUID NOT NULL DEFAULT uuid_generate_v4(),
    language_name VARCHAR NOT NULL,
    language_icon_url  VARCHAR NULL,
    country VARCHAR NULL,
    resource_file_url VARCHAR NULL,
    created_date timestamp NULL,
    created_by BIGINT NULL,
    is_active BOOLEAN DEFAULT true
);

-- Alter  newly created table and makes owner to postgres;
alter table language_master owner to postgres;
