create table if not exists issuance_conversion_rate
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    currency_from  VARCHAR NOT NULL,
    currency_to  VARCHAR NOT NULL,
    base_rate numeric(40,20) DEFAULT 0.0,
    valid_from timestamp NULL,
    valid_to timestamp NULL,
    created_at timestamp NULL,
    is_active BOOLEAN DEFAULT true,
    created_by BIGINT NOT NULL,
    CONSTRAINT pk_issuance_conversion_rate PRIMARY KEY (id),
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id),
    CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES issuance_banks (id)
    );

create table if not exists issuance_conversion_rate_adjustment
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    currency_from  VARCHAR NOT NULL,
    currency_to  VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    percentage numeric(4, 2),
    valid_from timestamp NULL,
    valid_to timestamp NULL,
    created_at timestamp NULL,
    is_active BOOLEAN DEFAULT true,
    created_by BIGINT NOT NULL,
    CONSTRAINT pk_issuance_conversion_rate_adjustment PRIMARY KEY (id),
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id),
    CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES issuance_banks (id)
    );


