CREATE TABLE IF NOT EXISTS merchant_pos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pos_id      VARCHAR(255),
    merchant_id BIGINT,
    pos_name VARCHAR,
    CONSTRAINT pk_merchnat_pos PRIMARY KEY (id),
    FOREIGN KEY (merchant_id) REFERENCES merchant (id)
);

ALTER TABLE merchant
    ADD COLUMN IF NOT EXISTS pos_id BIGINT,
    ADD CONSTRAINT fk_merchant_pos FOREIGN KEY (pos_id) REFERENCES merchant_pos (id);

ALTER TABLE transaction_pos
    ADD COLUMN merchant_pos_id BIGINT,
ADD CONSTRAINT fk_merchant_pos FOREIGN KEY (merchant_pos_id) REFERENCES merchant_pos (id);

ALTER TABLE transaction_pos
    RENAME COLUMN merchantid TO merchant_id;
ALTER TABLE transaction_pos
    DROP COLUMN IF EXISTS posid;
ALTER TABLE transaction_pos
ALTER COLUMN merchant_id type BIGINT USING merchant_id::BIGINT,
    ADD CONSTRAINT fk_merchant FOREIGN KEY (merchant_id) REFERENCES merchant (id)


