CREATE TABLE contact
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nickname        VARCHAR(255)                            NOT NULL,
    user_account_id BIGINT,
    owner_id        BIGINT,
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

ALTER TABLE contact
    ADD CONSTRAINT FK_CONTACT_ON_OWNER FOREIGN KEY (owner_id) REFERENCES user_account (id);

ALTER TABLE contact
    ADD CONSTRAINT FK_CONTACT_ON_USERACCOUNT FOREIGN KEY (user_account_id) REFERENCES user_account (id);
