create table if not exists role
(
    role_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483645 CACHE 1 ),
    role_name     character varying(30),
    level_id      int,
    role_comments character varying(150),
    created_at    timestamp NULL,
    created_by    bigint,
    updated_at    timestamp NULL,
    updated_by    bigint,
    status        boolean,
    constraint role_pkey primary key (role_id),
    CONSTRAINT fk_roles_created_by FOREIGN KEY (created_by) REFERENCES user_account (id),
    CONSTRAINT fk_roles_updated_by FOREIGN KEY (updated_by) REFERENCES user_account (id)
    );

create table if not exists role_transaction
(
    role_transaction_id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2094967295 CACHE 1 ),
    role_id      int ,
    role_name     character varying(30),
    level_id      int,
    role_comments character varying(150),
    created_updated_at          timestamp NULL,
    created_updated_by          bigint,
    status        boolean,
    constraint role_transaction_pkey primary key (role_transaction_id),
    CONSTRAINT fk_role_transaction_created_updated_by FOREIGN KEY (created_updated_by) REFERENCES user_account (id)

    );

create table if not exists role_modules
(
    role_module_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2094967295 CACHE 1 ),
    role_id    int ,
    module_id int[],
    created_at timestamp NULL,
    created_by bigint,
    updated_at timestamp NULL,
    updated_by bigint,
    CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES role (role_id),
    CONSTRAINT fk_role_modules_created_by FOREIGN KEY (created_by) REFERENCES user_account (id),
    CONSTRAINT fk_role_modules_updated_by FOREIGN KEY (updated_by) REFERENCES user_account (id)
    );


create table if not exists role_modules_transaction
(
    role_module_transaction_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    role_id                     int,
    module_id                   int[],
    created_updated_at          timestamp NULL,
    created_updated_by          bigint,
    constraint role_modules_transaction_pkey primary key (role_module_transaction_id),
    CONSTRAINT fk_role_modules_transaction_created_updated_by FOREIGN KEY (created_updated_by) REFERENCES user_account (id)

    );
