
CREATE TABLE IF NOT EXISTS user_passcode
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_account_id 		     BIGINT          NOT NULL,
    passcode_hash            VARCHAR         NOT NULL,
    salt_version            VARCHAR         NULL,
    created_date timestamp NULL,
    created_by BIGINT NULL,
    modified_date timestamp NULL,
    modified_by BIGINT NULL,
    is_active BOOLEAN DEFAULT true,
    CONSTRAINT pk_user_passcode PRIMARY KEY (id),
    CONSTRAINT fk_user_account_id FOREIGN KEY (user_account_id) REFERENCES user_account (id)
    );