-- A new table for asset quantity;
create table if not exists asset_Quantity
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issuance_banks_id BIGINT NOT NULL,
    partner_institution_name  VARCHAR NULL,
    asset VARCHAR NOT NULL,
    min_transfer_amount numeric(20, 2) NULL,
    min_wallet_balance numeric(20, 2) NULL,
    api_call_code BIGINT NULL,
    is_active BOOLEAN DEFAULT true,
    created_date timestamp NULL,
    modified_date timestamp NULL,
    CONSTRAINT fk_issuance_banks_id FOREIGN KEY (issuance_banks_id) REFERENCES issuance_banks (id)
);
