-- Alter country master;
ALTER TABLE public.country
    ADD COLUMN if not exists created_by BIGINT NULL,
    ADD COLUMN if not exists modified_by BIGINT NULL,
    drop constraint if exists fk_created_by,
    drop constraint if exists fk_modified_by,
    ADD CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES user_account (id),
    ADD CONSTRAINT fk_modified_by FOREIGN KEY (modified_by) REFERENCES user_account (id);

-- Alter  language_master;
ALTER TABLE public.language_master
    ADD COLUMN if not exists language_display_name VARCHAR NULL,
    ADD COLUMN if not exists modified_date timestamp NULL,
    ADD COLUMN if not exists modified_by BIGINT NULL,
    drop constraint if exists fk_modified_by,
    ADD CONSTRAINT fk_modified_by FOREIGN KEY (modified_by) REFERENCES issuance_banks (id);

-- Alter  language_master table and foreign key constraint;
ALTER TABLE public.language_master
    ALTER COLUMN country TYPE BIGINT using country::bigint,
    drop constraint if exists fk_country,
    ADD CONSTRAINT  fk_country FOREIGN KEY (country) REFERENCES country (id);

-- Insert data in country table;

INSERT INTO public.country (country_code, country_name, country_image_url,is_active,created_date)
VALUES ('AF', 'Afghanistan', 'https://www.worldometers.info/img/flags/af-flag.gif',true,NOW()),
       ('AL', 'Albania', 'https://www.worldometers.info/img/flags/al-flag.gif',true,NOW()),
       ('AG', 'Algeria', 'https://www.worldometers.info/img/flags/ag-flag.gif',true,NOW()),
       ('AN', 'Andorra', 'https://www.worldometers.info/img/flags/an-flag.gif',true,NOW()),
       ('AO', 'Angola', 'https://www.worldometers.info/img/flags/ao-flag.gif',true,NOW()),
       ('AC', 'Antigua and Barbuda', 'https://www.worldometers.info/img/flags/ac-flag.gif',true,NOW()),
       ('AR', 'Argentina', 'https://www.worldometers.info/img/flags/ar-flag.gif',true,NOW()),
       ('AM', 'Armenia', 'https://www.worldometers.info/img/flags/am-flag.gif',true,NOW()),
       ('AS', 'Australia', 'https://www.worldometers.info/img/flags/as-flag.gif',true,NOW()),
       ('AU', 'Austria', 'https://www.worldometers.info/img/flags/au-flag.gif',true,NOW()),
       ('AJ', 'Azerbaijan', 'https://www.worldometers.info/img/flags/aj-flag.gif',true,NOW()),
       ('BF', 'Bahamas', 'https://www.worldometers.info/img/flags/bf-flag.gif',true,NOW()),
       ('BA', 'Bahrain', 'https://www.worldometers.info/img/flags/ba-flag.gif',true,NOW()),
       ('BG', 'Bangladesh', 'https://www.worldometers.info/img/flags/bg-flag.gif',true,NOW()),
       ('BB', 'Barbados', 'https://www.worldometers.info/img/flags/bb-flag.gif',true,NOW()),
       ('BO', 'Belarus', 'https://www.worldometers.info/img/flags/bo-flag.gif',true,NOW()),
       ('BE', 'Belgium', 'https://www.worldometers.info/img/flags/be-flag.gif',true,NOW()),
       ('BH', 'Belize', 'https://www.worldometers.info/img/flags/bh-flag.gif',true,NOW()),
       ('BN', 'Benin', 'https://www.worldometers.info/img/flags/bn-flag.gif',true,NOW()),
       ('BN', 'Bhutan', 'https://www.worldometers.info/img/flags/bn-flag.gif',true,NOW()),
       ('BN', 'Bolivia', 'https://www.worldometers.info/img/flags/bn-flag.gif',true,NOW()),
       ('BK', 'Bosnia and Herzegovina', 'https://www.worldometers.info/img/flags/bk-flag.gif',true,NOW()),
       ('BC', 'Botswana', 'https://www.worldometers.info/img/flags/bc-flag.gif',true,NOW()),
       ('BL', 'Brazil', 'https://www.worldometers.info/img/flags/bl-flag.gif',true,NOW()),
       ('BX', 'Brunei', 'https://www.worldometers.info/img/flags/bx-flag.gif',true,NOW()),
       ('BU', 'Bulgaria', 'https://www.worldometers.info/img/flags/bu-flag.gif',true,NOW()),
       ('UV', 'Burkina Faso', 'https://www.worldometers.info/img/flags/uv-flag.gif',true,NOW()),
       ('BY', 'Burundi', 'https://www.worldometers.info/img/flags/by-flag.gif',true,NOW()),
       ('IV', 'Côte d''Ivoire', 'https://www.worldometers.info/img/flags/iv-flag.gif',true,NOW()),
       ('CV', 'Cabo Verde', 'https://www.worldometers.info/img/flags/cv-flag.gif',true,NOW()),
       ('CB', 'Cambodia', 'https://www.worldometers.info/img/flags/cb-flag.gif',true,NOW()),
       ('CM', 'Cameroon', 'https://www.worldometers.info/img/flags/cm-flag.gif',true,NOW()),
       ('CA', 'Canada', 'https://www.worldometers.info/img/flags/ca-flag.gif',true,NOW()),
       ('CT', 'CAR', 'https://www.worldometers.info/img/flags/ct-flag.gif',true,NOW()),
       ('CD', 'Chad', 'https://www.worldometers.info/img/flags/cd-flag.gif',true,NOW()),
       ('CI', 'Chile', 'https://www.worldometers.info/img/flags/ci-flag.gif',true,NOW()),
       ('CH', 'China', 'https://www.worldometers.info/img/flags/ch-flag.gif',true,NOW()),
       ('CO', 'Colombia', 'https://www.worldometers.info/img/flags/co-flag.gif',true,NOW()),
       ('CN', 'Comoros', 'https://www.worldometers.info/img/flags/cn-flag.gif',true,NOW()),
       ('CG', 'Congo', 'https://www.worldometers.info/img/flags/cg-flag.gif',true,NOW()),
       ('CS', 'Costa Rica', 'https://www.worldometers.info/img/flags/cs-flag.gif',true,NOW()),
       ('HR', 'Croatia', 'https://www.worldometers.info/img/flags/hr-flag.gif',true,NOW()),
       ('CU', 'Cuba', 'https://www.worldometers.info/img/flags/cu-flag.gif',true,NOW()),
       ('CY', 'Cyprus', 'https://www.worldometers.info/img/flags/cy-flag.gif',true,NOW()),
       ('EZ', 'Czechia', 'https://www.worldometers.info/img/flags/ez-flag.gif',true,NOW()),
       ('DA', 'Denmark', 'https://www.worldometers.info/img/flags/da-flag.gif',true,NOW()),
       ('DJ', 'Djibouti', 'https://www.worldometers.info/img/flags/dj-flag.gif',true,NOW()),
       ('DO', 'Dominica', 'https://www.worldometers.info/img/flags/do-flag.gif',true,NOW()),
       ('DR', 'Dominican Republic', 'https://www.worldometers.info/img/flags/dr-flag.gif',true,NOW()),
       ('KN', 'DPRK', 'https://www.worldometers.info/img/flags/kn-flag.gif',true,NOW()),
       ('CONGO', 'DRC', 'https://www.worldometers.info/img/flags/congo-flag.gif',true,NOW()),
       ('EC', 'Ecuador', 'https://www.worldometers.info/img/flags/ec-flag.gif',true,NOW()),
       ('EG', 'Egypt', 'https://www.worldometers.info/img/flags/eg-flag.gif',true,NOW()),
       ('ES', 'El Salvador', 'https://www.worldometers.info/img/flags/es-flag.gif',true,NOW()),
       ('EK', 'Equatorial Guinea', 'https://www.worldometers.info/img/flags/ek-flag.gif',true,NOW()),
       ('ER', 'Eritrea', 'https://www.worldometers.info/img/flags/er-flag.gif',true,NOW()),
       ('EN', 'Estonia', 'https://www.worldometers.info/img/flags/en-flag.gif',true,NOW()),
       ('WZ', 'Eswatini', 'https://www.worldometers.info/img/flags/wz-flag.gif',true,NOW()),
       ('ET', 'Ethiopia', 'https://www.worldometers.info/img/flags/et-flag.gif',true,NOW()),
       ('FJ', 'Fiji', 'https://www.worldometers.info/img/flags/fj-flag.gif',true,NOW()),
       ('FI', 'Finland', 'https://www.worldometers.info/img/flags/fi-flag.gif',true,NOW()),
       ('FR', 'France', 'https://www.worldometers.info/img/flags/fr-flag.gif',true,NOW()),
       ('GB', 'Gabon', 'https://www.worldometers.info/img/flags/gb-flag.gif',true,NOW()),
       ('GA', 'Gambia', 'https://www.worldometers.info/img/flags/ga-flag.gif',true,NOW()),
       ('GG', 'Georgia', 'https://www.worldometers.info/img/flags/gg-flag.gif',true,NOW()),
       ('GM', 'Germany', 'https://www.worldometers.info/img/flags/gm-flag.gif',true,NOW()),
       ('GH', 'Ghana', 'https://www.worldometers.info/img/flags/gh-flag.gif',true,NOW()),
       ('GR', 'Greece', 'https://www.worldometers.info/img/flags/gr-flag.gif',true,NOW()),
       ('GJ', 'Grenada', 'https://www.worldometers.info/img/flags/gj-flag.gif',true,NOW()),
       ('GT', 'Guatemala', 'https://www.worldometers.info/img/flags/gt-flag.gif',true,NOW()),
       ('GV', 'Guinea', 'https://www.worldometers.info/img/flags/gv-flag.gif',true,NOW()),
       ('PU', 'Guinea-Bissau', 'https://www.worldometers.info/img/flags/pu-flag.gif',true,NOW()),
       ('GY', 'Guyana', 'https://www.worldometers.info/img/flags/gy-flag.gif',true,NOW()),
       ('HA', 'Haiti', 'https://www.worldometers.info/img/flags/ha-flag.gif',true,NOW()),
       ('VT', 'Holy See', 'https://www.worldometers.info/img/flags/vt-flag.gif',true,NOW()),
       ('HO', 'Honduras', 'https://www.worldometers.info/img/flags/ho-flag.gif',true,NOW()),
       ('HU', 'Hungary', 'https://www.worldometers.info/img/flags/hu-flag.gif',true,NOW()),
       ('IC', 'Iceland', 'https://www.worldometers.info/img/flags/ic-flag.gif',true,NOW()),
       ('IN', 'India', 'https://www.worldometers.info/img/flags/in-flag.gif',true,NOW()),
       ('ID', 'Indonesia', 'https://www.worldometers.info/img/flags/id-flag.gif',true,NOW()),
       ('IR', 'Iran', 'https://www.worldometers.info/img/flags/ir-flag.gif',true,NOW()),
       ('IZ', 'Iraq', 'https://www.worldometers.info/img/flags/iz-flag.gif',true,NOW()),
       ('EI', 'Ireland', 'https://www.worldometers.info/img/flags/ei-flag.gif',true,NOW()),
       ('IS', 'Israel', 'https://www.worldometers.info/img/flags/is-flag.gif',true,NOW()),
       ('IT', 'Italy', 'https://www.worldometers.info/img/flags/it-flag.gif',true,NOW()),
       ('JM', 'Jamaica', 'https://www.worldometers.info/img/flags/jm-flag.gif',true,NOW()),
       ('JA', 'Japan', 'https://www.worldometers.info/img/flags/ja-flag.gif',true,NOW()),
       ('JO', 'Jordan', 'https://www.worldometers.info/img/flags/jo-flag.gif',true,NOW()),
       ('KZ', 'Kazakhstan', 'https://www.worldometers.info/img/flags/kz-flag.gif',true,NOW()),
       ('KE', 'Kenya', 'https://www.worldometers.info/img/flags/ke-flag.gif',true,NOW()),
       ('kr', 'Kiribati', 'https://www.worldometers.info/img/flags/kr-flag.gif',true,NOW()),
       ('ku', 'Kuwait', 'https://www.worldometers.info/img/flags/ku-flag.gif',true,NOW()),
       ('kg', 'Kyrgyzstan', 'https://www.worldometers.info/img/flags/kg-flag.gif',true,NOW()),
       ('LA', 'Laos', 'https://www.worldometers.info/img/flags/la-flag.gif',true,NOW()),
       ('LG', 'Latvia', 'https://www.worldometers.info/img/flags/lg-flag.gif',true,NOW()),
       ('LE', 'Lebanon', 'https://www.worldometers.info/img/flags/le-flag.gif',true,NOW()),
       ('LT', 'Lesotho', 'https://www.worldometers.info/img/flags/lt-flag.gif',true,NOW()),
       ('LI', 'Liberia', 'https://www.worldometers.info/img/flags/li-flag.gif',true,NOW()),
       ('LY', 'Libya', 'https://www.worldometers.info/img/flags/ly-flag.gif',true,NOW()),
       ('LS', 'Liechtenstein', 'https://www.worldometers.info/img/flags/ls-flag.gif',true,NOW()),
       ('LH', 'Lithuania', 'https://www.worldometers.info/img/flags/lh-flag.gif',true,NOW()),
       ('LU', 'Luxembourg', 'https://www.worldometers.info/img/flags/lu-flag.gif',true,NOW()),
       ('MA', 'Madagascar', 'https://www.worldometers.info/img/flags/ma-flag.gif',true,NOW()),
       ('MI', 'Malawi', 'https://www.worldometers.info/img/flags/mi-flag.gif',true,NOW()),
       ('MY', 'Malaysia', 'https://www.worldometers.info/img/flags/my-flag.gif',true,NOW()),
       ('MV', 'Maldives', 'https://www.worldometers.info/img/flags/mv-flag.gif',true,NOW()),
       ('ML', 'Mali', 'https://www.worldometers.info/img/flags/ml-flag.gif',true,NOW()),
       ('MT', 'Malta', 'https://www.worldometers.info/img/flags/mt-flag.gif',true,NOW()),
       ('RM', 'Marshall Islands', 'https://www.worldometers.info/img/flags/rm-flag.gif',true,NOW()),
       ('MR', 'Mauritania', 'https://www.worldometers.info/img/flags/mr-flag.gif',true,NOW()),
       ('MP', 'Mauritius', 'https://www.worldometers.info/img/flags/mp-flag.gif',true,NOW()),
       ('MZ', 'Mexico', 'https://www.worldometers.info/img/flags/mx-flag.gif',true,NOW()),
       ('FM', 'Micronesia', 'https://www.worldometers.info/img/flags/fm-flag.gif',true,NOW()),
       ('MI', 'Moldova', 'https://www.worldometers.info/img/flags/mi-flag.gif',true,NOW()),
       ('MN', 'Monaco', 'https://www.worldometers.info/img/flags/mn-flag.gif',true,NOW()),
       ('MG', 'Mongolia', 'https://www.worldometers.info/img/flags/mg-flag.gif',true,NOW()),
       ('MJ', 'Montenegro', 'https://www.worldometers.info/img/flags/mj-flag.gif',true,NOW()),
       ('MO', 'Morocco', 'https://www.worldometers.info/img/flags/mo-flag.gif',true,NOW()),
       ('MZ', 'Mozambique', 'https://www.worldometers.info/img/flags/mz-flag.gif',true,NOW()),
       ('BM', 'Myanmar', 'https://www.worldometers.info/img/flags/bm-flag.gif',true,NOW()),
       ('WA', 'Namibia', 'https://www.worldometers.info/img/flags/wa-flag.gif',true,NOW()),
       ('NR', 'Nauru', 'https://www.worldometers.info/img/flags/nr-flag.gif',true,NOW()),
       ('NP', 'Nepal', 'https://www.worldometers.info/img/flags/np-flag.gif',true,NOW()),
       ('NL', 'Netherlands', 'https://www.worldometers.info/img/flags/nl-flag.gif',true,NOW()),
       ('Nz', 'New Zealand', 'https://www.worldometers.info/img/flags/nz-flag.gif',true,NOW()),
       ('NU', 'Nicaragua', 'https://www.worldometers.info/img/flags/nu-flag.gif',true,NOW()),
       ('NG', 'Niger', 'https://www.worldometers.info/img/flags/ng-flag.gif',true,NOW()),
       ('NI', 'Nigeria', 'https://www.worldometers.info/img/flags/ni-flag.gif',true,NOW()),
       ('MK', 'North Macedonia', 'https://www.worldometers.info/img/flags/mk-flag.gif',true,NOW()),
       ('NO', 'Norway', 'https://www.worldometers.info/img/flags/no-flag.gif',true,NOW()),
       ('MU', 'Oman', 'https://www.worldometers.info/img/flags/mu-flag.gif',true,NOW()),
       ('PK', 'Pakistan', 'https://www.worldometers.info/img/flags/pk-flag.gif',true,NOW()),
       ('PS', 'Palau', 'https://www.worldometers.info/img/flags/ps-flag.gif',true,NOW()),
       ('PM', 'Panama', 'https://www.worldometers.info/img/flags/pm-flag.gif',true,NOW()),
       ('PP', 'Papua New Guinea', 'https://www.worldometers.info/img/flags/pp-flag.gif',true,NOW()),
       ('PA', 'Paraguay', 'https://www.worldometers.info/img/flags/pa-flag.gif',true,NOW()),
       ('PE', 'Peru', 'https://www.worldometers.info/img/flags/pe-flag.gif',true,NOW()),
       ('RP', 'Philippines', 'https://www.worldometers.info/img/flags/rp-flag.gif',true,NOW()),
       ('PL', 'Poland', 'https://www.worldometers.info/img/flags/pl-flag.gif',true,NOW()),
       ('PO', 'Portugal', 'https://www.worldometers.info/img/flags/po-flag.gif',true,NOW()),
       ('QA', 'Qatar', 'https://www.worldometers.info/img/flags/qa-flag.gif',true,NOW()),
       ('RO', 'Romania', 'https://www.worldometers.info/img/flags/ro-flag.gif',true,NOW()),
       ('RS', 'Russia', 'https://www.worldometers.info/img/flags/rs-flag.gif',true,NOW()),
       ('RW', 'Rwanda', 'https://www.worldometers.info/img/flags/rw-flag.gif',true,NOW()),
       ('SC', 'Saint Kitts and Nevis', 'https://www.worldometers.info/img/flags/sc-flag.gif',true,NOW()),
       ('ST', 'Saint Lucia', 'https://www.worldometers.info/img/flags/st-flag.gif',true,NOW()),
       ('WS', 'Samoa', 'https://www.worldometers.info/img/flags/ws-flag.gif',true,NOW()),
       ('SM', 'San Marino', 'https://www.worldometers.info/img/flags/sm-flag.gif',true,NOW()),
       ('TP', 'Sao Tome and Principe', 'https://www.worldometers.info/img/flags/tp-flag.gif',true,NOW()),
       ('SA', 'Saudi Arabia', 'https://www.worldometers.info/img/flags/sa-flag.gif',true,NOW()),
       ('SG', 'Senegal', 'https://www.worldometers.info/img/flags/sg-flag.gif',true,NOW()),
       ('RI', 'Serbia', 'https://www.worldometers.info/img/flags/ri-flag.gif',true,NOW()),
       ('SE', 'Seychelles', 'https://www.worldometers.info/img/flags/se-flag.gif',true,NOW()),
       ('SL', 'Sierra Leone', 'https://www.worldometers.info/img/flags/sl-flag.gif',true,NOW()),
       ('SN', 'Singapore', 'https://www.worldometers.info/img/flags/sn-flag.gif',true,NOW()),
       ('LO', 'Slovakia', 'https://www.worldometers.info/img/flags/lo-flag.gif',true,NOW()),
       ('SI', 'Slovenia', 'https://www.worldometers.info/img/flags/si-flag.gif',true,NOW()),
       ('BP', 'Solomon Islands', 'https://www.worldometers.info/img/flags/bp-flag.gif',true,NOW()),
       ('SO', 'Somalia', 'https://www.worldometers.info/img/flags/so-flag.gif',true,NOW()),
       ('SF', 'South Africa', 'https://www.worldometers.info/img/flags/sf-flag.gif',true,NOW()),
       ('KS', 'South Korea', 'https://www.worldometers.info/img/flags/ks-flag.gif',true,NOW()),
       ('OD', 'South Sudan', 'https://www.worldometers.info/img/flags/od-flag.gif',true,NOW()),
       ('SP', 'Spain', 'https://www.worldometers.info/img/flags/sp-flag.gif',true,NOW()),
       ('CE', 'Sri Lanka', 'https://www.worldometers.info/img/flags/ce-flag.gif',true,NOW()),
       ('VC', 'St. Vincent Grenadines', 'https://www.worldometers.info/img/flags/vc-flag.gif',true,NOW()),
       ('PL', 'State of Palestine', 'https://www.worldometers.info/img/flags/palestine-flag.gif',true,NOW()),
       ('SU', 'Sudan', 'https://www.worldometers.info/img/flags/su-flag.gif',true,NOW()),
       ('NS', 'Suriname', 'https://www.worldometers.info/img/flags/ns-flag.gif',true,NOW()),
       ('SW', 'Sweden', 'https://www.worldometers.info/img/flags/sw-flag.gif',true,NOW()),
       ('SZ', 'Switzerland', 'https://www.worldometers.info/img/flags/sz-flag.gif',true,NOW()),
       ('SY', 'Syria', 'https://www.worldometers.info/img/flags/sy-flag.gif',true,NOW()),
       ('TI', 'Tajikistan', 'https://www.worldometers.info/img/flags/ti-flag.gif',true,NOW()),
       ('TZ', 'Tanzania', 'https://www.worldometers.info/img/flags/tz-flag.gif',true,NOW()),
       ('TH', 'Thailand', 'https://www.worldometers.info/img/flags/th-flag.gif',true,NOW()),
       ('TT', 'Timor-Leste', 'https://www.worldometers.info/img/flags/tt-flag.gif',true,NOW()),
       ('TO', 'Togo', 'https://www.worldometers.info/img/flags/to-flag.gif',true,NOW()),
       ('TN', 'Tonga', 'https://www.worldometers.info/img/flags/tn-flag.gif',true,NOW()),
       ('TD', 'Trinidad and Tobago', 'https://www.worldometers.info/img/flags/td-flag.gif',true,NOW()),
       ('TS', 'Tunisia', 'https://www.worldometers.info/img/flags/ts-flag.gif',true,NOW()),
       ('TU', 'Turkey', 'https://www.worldometers.info/img/flags/tu-flag.gif',true,NOW()),
       ('TX', 'Turkmenistan', 'https://www.worldometers.info/img/flags/tx-flag.gif',true,NOW()),
       ('TV', 'Tuvalu', 'https://www.worldometers.info/img/flags/tv-flag.gif',true,NOW()),
       ('AE', 'U.A.E.', 'https://www.worldometers.info/img/flags/ae-flag.gif',true,NOW()),
       ('UK', 'U.K.', 'https://www.worldometers.info/img/flags/uk-flag.gif',true,NOW()),
       ('US', 'U.S.', 'https://www.worldometers.info/img/flags/us-flag.gif',true,NOW()),
       ('UG', 'Uganda', 'https://www.worldometers.info/img/flags/ug-flag.gif',true,NOW()),
       ('UP', 'Ukraine', 'https://www.worldometers.info/img/flags/up-flag.gif',true,NOW()),
       ('UY', 'Uruguay', 'https://www.worldometers.info/img/flags/uy-flag.gif',true,NOW()),
       ('UZ', 'Uzbekistan', 'https://www.worldometers.info/img/flags/uz-flag.gif',true,NOW()),
       ('NH', 'Vanuatu', 'https://worldometers.info/img/flags/nh-flag.gif',true,NOW()),
       ('VE', 'Venezuela', 'https://www.worldometers.info/img/flags/ve-flag.gif',true,NOW()),
       ('VM', 'Vietnam', 'https://www.worldometers.info/img/flags/vm-flag.gif',true,NOW()),
       ('YE', 'Yemen', 'https://www.worldometers.info/img/flags/ym-flag.gif',true,NOW()),
       ('ZA', 'Zambia', 'https://www.worldometers.info/img/flags/za-flag.gif',true,NOW()),
       ('ZI', 'Zimbabwe', 'https://www.worldometers.info/img/flags/zi-flag.gif',true,NOW())
;
