package com.wadzpay.ddflibrary.utils;

import java.util.HashMap;

public class ConstantsActivity {
    public static String STR_RADIO_OPTION = "";
    public static String STR_CURRENCY_FIAT_TYPE = "FIAT";
    public static String STR_EXT_POS_ID = "extPosId";
    public static String STR_EXT_POS_SEQUENCE_NUMBER = "extPosSequenceNo";
    public static String STR_EXT_POS_TRANSACTION_ID = "extPosTransactionId";
//    public static String STR_CURRENCY_CRYPTO_TYPE = "BTC";
    public static String STR_CURRENCY_ET = "";
    public static String STR_CURRENCY_CODE = "";
    public static String STR_SAR_CODE = "SAR*";
    public static String STR_TOKEN_CODE = "";
    public static String STR_CURRENCY_NAME = "";
    public static String STR_CURRENCY_AMOUNT = "";
    public static String STR_TRANSACTION_STATUS = "";
    public static String STR_CURRENCY_FEE_AMOUNT = "0.001";
    public static String STR_CURRENCY_TOTAL_AMOUNT = "";
    public static String FLAG_AMPLIFY_NAME = "AMPLIFY_NAME";
    public static String FLAG_AMPLIFY_RESIGN = "AMPLIFY_RESIGN";
    public static String FLAG_AMPLIFY_LOGIN = "AMPLIFY_LOGIN";
    public static String FLAG_AMPLIFY_PAY = "AMPLIFY_PAY";
    public static String FLAG_ENVIRONMENT = "";
    public static String FLAG_DDF_GEIDEA_ENVIRONMENT = "DDF";
    public static String FLAG_DEV = "DEV";
    public static String FLAG_TEST = "TEST";
    public static String FLAG_UAT = "UAT";
    public static String FLAG_PROD = "PROD";
    public static String FLAG_POC = "POC";
    public static String FLAG_DDF_UAT = "DDF-UAT";
    public static String FLAG_DDF_PROD = "DDF-PROD";
    public static String FLAG_GEIDEA_DEV = "GEIDEA-DEV";
    public static String FLAG_GEIDEA_TEST = "GEIDEA-TEST";
    public static String FLAG_GEIDEA_UAT = "GEIDEA-UAT";
    public static HashMap<String, Integer> hmCryptoImages = new HashMap<>();
    public static int INT_CURRENT_IMAGE_SPINNER = 0;
    public static int INT_QR_TIMER = 10;
    public static int INT_QR_TRANSACTION_TIMER = 6000;
    public static String STR_EMAIL_ID = "";
    public static String STR_NEW_PASSWORD = "";
    public static String STR_EMAIL_CODE = "";
    public static String STR_QR_FORMAT = "";
    public static String STR_FLAG_CHOICE_DIALOG = "";
    public static String STR_FLAG_CHOICE_AMOUNT_DIALOG = "AMOUNT";
    public static String STR_FLAG_CHOICE_QR_FORMAT_DIALOG = "QR_FORMAT";
//    public static String STR_FLAG_DELETE_ACCOUNT_DIALOG = "DELETE_ACCOUNT";
    public static String STR_FLAG_DIALOG = "DEFAULT";
    public static String STR_FORMAT_ET = "QR Format 5";
    public static String STR_FORMAT_TITLE = "QR Address";
    public static String STR_PASSWORD_CHANGES = "";
    public static boolean flag_fiat_selected = false;
    public static String STR_USER_ID = "";
    public static String STR_KEY_SP_USER_EMAIL = "USER_EMAIL";
    public static String STR_KEY_SP_USER_PASSWORD = "USER_PASSWORD";
    public static String STR_USER_EMAIL = "";
    public static String STR_USER_PASSWORD = "";
    public static String FLAG_STR_THANK_YOU = "";
    public static long flag_seconds = 60;
    public static boolean flag_clear_fields = false;
}
