package com.vacuumlabs.wadzpay.acquireradministration

import com.vacuumlabs.wadzpay.acquireradministration.dto.AggregatorDTO
import com.vacuumlabs.wadzpay.acquireradministration.dto.InstitutionDTO
import com.vacuumlabs.wadzpay.acquireradministration.dto.MerchantAcquirerDTO
import com.vacuumlabs.wadzpay.acquireradministration.dto.MerchantGroupDTO
import com.vacuumlabs.wadzpay.acquireradministration.dto.OutletDTO
import com.vacuumlabs.wadzpay.acquireradministration.dto.SubMerchantAcquirerDTO
import com.vacuumlabs.wadzpay.acquireradministration.model.Aggregator
import com.vacuumlabs.wadzpay.acquireradministration.model.EntityAddress
import com.vacuumlabs.wadzpay.acquireradministration.model.EntityAdminDetails
import com.vacuumlabs.wadzpay.acquireradministration.model.EntityBankDetails
import com.vacuumlabs.wadzpay.acquireradministration.model.EntityContactDetails
import com.vacuumlabs.wadzpay.acquireradministration.model.EntityInfo
import com.vacuumlabs.wadzpay.acquireradministration.model.EntityOthers
import com.vacuumlabs.wadzpay.acquireradministration.model.Institution
import com.vacuumlabs.wadzpay.acquireradministration.model.MerchantAcquirer
import com.vacuumlabs.wadzpay.acquireradministration.model.MerchantGroup
import com.vacuumlabs.wadzpay.acquireradministration.model.Outlet
import com.vacuumlabs.wadzpay.acquireradministration.model.SubMerchantAcquirer
import org.springframework.stereotype.Service

@Service
class DTOEntityConverterService {

    fun toOutletModel(dto: OutletDTO): Outlet {
        var outlet = Outlet()
        var others = EntityOthers()
        var info = EntityInfo()
        outlet.aggregatorPreferenceId = dto.aggregatorPreferenceId
        outlet.insitutionPreferenceId = dto.insitutionPreferenceId
        outlet.merchantGroupPreferenceId = dto.merchantGroupPreferenceId
        outlet.merchantAcquirerPreferenceId = dto.merchantAcquirerPreferenceId
        outlet.subMerchantPreferenceId = dto.subMerchantPreferenceId
        outlet.outletId = dto.outletId
        outlet.outletLogo = dto.outletLogo
        outlet.outletStatus = dto.outletStatus
        outlet.outletName = dto.outletName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        outlet.address = address
        outlet.others = others
        outlet.contactDetails = contact
        outlet.bankDetails = bank
        outlet.adminDetails = admin
        outlet.info = info
        outlet.error = dto.error
        return outlet
    }
    fun toOutletModel1(dto: AggregatorDTO): Outlet {
        var outlet = Outlet()
        var others = EntityOthers()
        var info = EntityInfo()
        outlet.type = dto.type
        outlet.aggregatorPreferenceId = dto.aggregatorPreferenceId
        outlet.insitutionPreferenceId = dto.insitutionPreferenceId
        outlet.merchantGroupPreferenceId = dto.merchantGroupPreferenceId
        outlet.merchantAcquirerPreferenceId = dto.merchantAcquirerId
        outlet.subMerchantPreferenceId = dto.subMerchantAcquirerId
        outlet.outletId = dto.outletId
        outlet.outletLogo = dto.outletLogo
        outlet.outletStatus = dto.outletStatus
        outlet.outletName = dto.outletName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        outlet.address = address
        outlet.others = others
        outlet.contactDetails = contact
        outlet.bankDetails = bank
        outlet.adminDetails = admin
        outlet.info = info
        outlet.error = dto.error
        return outlet
    }

    fun toAggregatorModel(dto: AggregatorDTO): Aggregator {

        var aggregator = Aggregator()
        var others = EntityOthers()
        var info = EntityInfo()
        aggregator.type = dto.type
        aggregator.aggregatorPreferenceId = dto.aggregatorPreferenceId
        aggregator.aggregatorName = dto.aggregatorName
        aggregator.aggregatorLogo = dto.aggregatorLogo
        aggregator.aggregatorStatus = dto.aggregatorStatus
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        aggregator.address = address
        aggregator.others = others
        aggregator.contactDetails = contact
        aggregator.bankDetails = bank
        aggregator.adminDetails = admin
        aggregator.info = info
        aggregator.error = dto.error
        return aggregator
    }
    fun toInstitution1(dto: AggregatorDTO): Institution {
        var institution = Institution()
        var others = EntityOthers()
        var info = EntityInfo()
        institution.type = dto.type
        institution.aggregatorPreferenceId = dto.aggregatorPreferenceId
        institution.institutionId = dto.institutionId
        institution.institutionLogo = dto.institutionLogo
        institution.insitutionPreferenceId = dto.insitutionPreferenceId
        institution.insitutionName = dto.insitutionName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        institution.address = address
        institution.others = others
        institution.contactDetails = contact
        institution.bankDetails = bank
        institution.adminDetails = admin
        institution.info = info
        institution.error = dto.error
        institution.insitutionStatus = dto.institutionStatus!!
        return institution
    }

    fun toInstitution(dto: InstitutionDTO): Institution {
        var institution = Institution()
        var others = EntityOthers()
        var info = EntityInfo()
        institution.aggregatorPreferenceId = dto.aggregatorPreferenceId
        institution.institutionId = dto.institutionId
        institution.institutionLogo = dto.institutionLogo
        institution.insitutionPreferenceId = dto.insitutionPreferenceId
        institution.insitutionName = dto.insitutionName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        institution.address = address
        institution.others = others
        institution.contactDetails = contact
        institution.bankDetails = bank
        institution.adminDetails = admin
        institution.info = info
        institution.error = dto.error
        if (dto.institutionStatus != null)
            institution.insitutionStatus = dto.institutionStatus!!
        return institution
    }
    fun toMerchantGroup1(dto: AggregatorDTO): MerchantGroup {
        var merchantGroup = MerchantGroup()
        var others = EntityOthers()
        var info = EntityInfo()
        merchantGroup.type = dto.type
        merchantGroup.aggregatorPreferenceId = dto.aggregatorPreferenceId
        merchantGroup.insitutionPreferenceId = dto.insitutionPreferenceId
        merchantGroup.merchantGroupPreferenceId = dto.merchantGroupPreferenceId
        merchantGroup.merchantGroupLogo = dto.merchantGroupLogo
        merchantGroup.merchantGroupStatus = dto.merchantGroupStatus
        merchantGroup.merchantGroupName = dto.merchantGroupName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        merchantGroup.address = address
        merchantGroup.others = others
        merchantGroup.contactDetails = contact
        merchantGroup.bankDetails = bank
        merchantGroup.adminDetails = admin
        merchantGroup.info = info
        merchantGroup.error = dto.error
        return merchantGroup
    }
    fun toMerchantGroup(dto: MerchantGroupDTO): MerchantGroup {
        var merchantGroup = MerchantGroup()
        var others = EntityOthers()
        var info = EntityInfo()
        merchantGroup.aggregatorPreferenceId = dto.aggregatorPreferenceId
        merchantGroup.insitutionPreferenceId = dto.insitutionPreferenceId
        merchantGroup.merchantGroupPreferenceId = dto.merchantGroupPreferenceId
        merchantGroup.merchantGroupLogo = dto.merchantGroupLogo
        merchantGroup.merchantGroupStatus = dto.merchantGroupStatus
        merchantGroup.merchantGroupName = dto.merchantGroupName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        merchantGroup.address = address
        merchantGroup.others = others
        merchantGroup.contactDetails = contact
        merchantGroup.bankDetails = bank
        merchantGroup.adminDetails = admin
        merchantGroup.info = info
        merchantGroup.error = dto.error
        return merchantGroup
    }
    fun toMerchant(dto: MerchantAcquirerDTO): MerchantAcquirer {
        var merchantAcquirer = MerchantAcquirer()
        var others = EntityOthers()
        var info = EntityInfo()
        merchantAcquirer.aggregatorPreferenceId = dto.aggregatorPreferenceId
        merchantAcquirer.insitutionPreferenceId = dto.insitutionPreferenceId
        merchantAcquirer.merchantGroupPreferenceId = dto.merchantGroupPreferenceId
        merchantAcquirer.merchantAcquirerId = dto.merchantAcquirerId
        merchantAcquirer.merchantAcquirerLogo = dto.merchantAcquirerLogo
        merchantAcquirer.merchantAcquirerStatus = dto.merchantStatus
        merchantAcquirer.merchantAcquirerName = dto.merchantAcquirerName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        merchantAcquirer.address = address
        merchantAcquirer.others = others
        merchantAcquirer.contactDetails = contact
        merchantAcquirer.bankDetails = bank
        merchantAcquirer.adminDetails = admin
        merchantAcquirer.info = info
        merchantAcquirer.error = dto.error
        return merchantAcquirer
    }
    fun toMerchant1(dto: AggregatorDTO): MerchantAcquirer {
        var merchantAcquirer = MerchantAcquirer()
        var others = EntityOthers()
        var info = EntityInfo()
        merchantAcquirer.type = dto.type
        merchantAcquirer.aggregatorPreferenceId = dto.aggregatorPreferenceId
        merchantAcquirer.insitutionPreferenceId = dto.insitutionPreferenceId
        merchantAcquirer.merchantGroupPreferenceId = dto.merchantGroupPreferenceId
        merchantAcquirer.merchantAcquirerId = dto.merchantAcquirerId
        merchantAcquirer.merchantAcquirerLogo = dto.merchantAcquirerLogo
        merchantAcquirer.merchantAcquirerStatus = dto.merchantAcquirerStatus
        merchantAcquirer.merchantAcquirerName = dto.merchantAcquirerName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        merchantAcquirer.address = address
        merchantAcquirer.others = others
        merchantAcquirer.contactDetails = contact
        merchantAcquirer.bankDetails = bank
        merchantAcquirer.adminDetails = admin
        merchantAcquirer.info = info
        merchantAcquirer.error = dto.error
        return merchantAcquirer
    }
    fun toSubMerchant1(dto: AggregatorDTO): SubMerchantAcquirer {
        var subMerchantAcquirer = SubMerchantAcquirer()
        var others = EntityOthers()
        var info = EntityInfo()
        subMerchantAcquirer.type = dto.type
        subMerchantAcquirer.aggregatorPreferenceId = dto.aggregatorPreferenceId
        subMerchantAcquirer.insitutionPreferenceId = dto.insitutionPreferenceId
        subMerchantAcquirer.merchantGroupPreferenceId = dto.merchantGroupPreferenceId
        subMerchantAcquirer.merchantAcquirerPreferenceId = dto.merchantAcquirerId
        subMerchantAcquirer.subMerchantAcquirerId = dto.subMerchantAcquirerId
        subMerchantAcquirer.subMerchantAcquirerLogo = dto.subMerchantAcquirerLogo
        subMerchantAcquirer.subMerchantAcquirerStatus = dto.subMerchantAcquirerStatus
        subMerchantAcquirer.subMerchantAcquirerName = dto.subMerchantAcquirerName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        subMerchantAcquirer.address = address
        subMerchantAcquirer.others = others
        subMerchantAcquirer.contactDetails = contact
        subMerchantAcquirer.bankDetails = bank
        subMerchantAcquirer.adminDetails = admin
        subMerchantAcquirer.info = info
        subMerchantAcquirer.error = dto.error
        return subMerchantAcquirer
    }

    fun toSubMerchant(dto: SubMerchantAcquirerDTO): SubMerchantAcquirer {
        var subMerchantAcquirer = SubMerchantAcquirer()
        var others = EntityOthers()
        var info = EntityInfo()
        subMerchantAcquirer.aggregatorPreferenceId = dto.aggregatorPreferenceId
        subMerchantAcquirer.insitutionPreferenceId = dto.insitutionPreferenceId
        subMerchantAcquirer.merchantGroupPreferenceId = dto.merchantGroupPreferenceId
        subMerchantAcquirer.merchantAcquirerPreferenceId = dto.merchantAcquirerPreferenceId
        subMerchantAcquirer.subMerchantAcquirerId = dto.subMerchantAcquirerId
        subMerchantAcquirer.subMerchantAcquirerLogo = dto.subMerchantAcquirerLogo
        subMerchantAcquirer.subMerchantAcquirerStatus = dto.subMerchantStatus
        subMerchantAcquirer.subMerchantAcquirerName = dto.subMerchantAcquirerName
        others.entityOthersActivationDate = dto.entityOthersActivationDate
        others.entityOthersApprovalWorkFlow = dto.entityOthersApprovalWorkFlow
        others.entityOthersMerchantOfflineTxn = dto.entityOthersMerchantOfflineTxn
        others.entityOthersCustomerOfflineTxn = dto.entityOthersCustomerOfflineTxn
        info.entityInfoAbbrevation = dto.entityInfoAbbrevation
        info.entityInfoDescription = dto.entityInfoDescription
        info.entityInfoLogo = dto.entityInfoLogo
        info.entityInfoRegion = dto.entityInfoRegion
        info.entityInfoType = dto.entityInfoType
        info.entityInfoTimezone = dto.entityInfoTimezone
        info.entityInfoDefaultDigitalCurrency = dto.entityInfoDefaultDigitalCurrency
        info.entityInfoBaseFiatCurrency = dto.entityInfoBaseFiatCurrency
        val address = EntityAddress()
        address.entityAddressAddressLine1 = dto.entityAddressAddressLine1
        address.entityAddressAddressLine2 = dto.entityAddressAddressLine2
        address.entityAddressAddressLine3 = dto.entityAddressAddressLine3
        address.entityAddressCity = dto.entityAddressCity
        address.entityAddressState = dto.entityAddressState
        address.entityAddressCountry = dto.entityAddressCountry
        address.entityAddressPostalCode = dto.entityAddressPostalCode
        val admin = EntityAdminDetails()
        admin.entityAdminDetailsFirstName = dto.entityAdminDetailsFirstName
        admin.entityAdminDetailsMiddleName = dto.entityAdminDetailsMiddleName
        admin.entityAdminDetailsLastName = dto.entityAdminDetailsLastName
        admin.entityAdminDetailsMobileNumber = dto.entityAdminDetailsMobileNumber
        admin.entityAdminDetailsEmailId = dto.entityAdminDetailsEmailId
        admin.entityAdminDetailsDepartment = dto.entityAdminDetailsDepartment
        val bank = EntityBankDetails()
        bank.entityBankDetailsBankAccountNumber = dto.entityBankDetailsBankAccountNumber
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankHolderName
        bank.entityBankDetailsBankName = dto.entityBankDetailsBankName
        bank.entityBankDetailsBranchCode = dto.entityBankDetailsBranchCode
        bank.entityBankDetailsBranchLocation = dto.entityBankDetailsBranchLocation
        val contact = EntityContactDetails()
        contact.entityContactDetailsFirstName = dto.entityContactDetailsFirstName
        contact.entityContactDetailsMiddleName = dto.entityContactDetailsMiddleName
        contact.entityContactDetailsLastName = dto.entityContactDetailsLastName
        contact.entityContactDetailsEmailId = dto.entityContactDetailsEmailId
        contact.entityContactDetailsMobileNumber = dto.entityContactDetailsMobileNumber
        contact.entityContactDetailsDesignation = dto.entityContactDetailsDesignation
        contact.entityContactDetailsDepartment = dto.entityContactDetailsDepartment
        subMerchantAcquirer.address = address
        subMerchantAcquirer.others = others
        subMerchantAcquirer.contactDetails = contact
        subMerchantAcquirer.bankDetails = bank
        subMerchantAcquirer.adminDetails = admin
        subMerchantAcquirer.info = info
        subMerchantAcquirer.error = dto.error
        return subMerchantAcquirer
    }

    fun toOutletDTO(outlet: Outlet): OutletDTO {
        var dto = OutletDTO()
        dto.aggregatorPreferenceId = outlet.aggregatorPreferenceId
        dto.insitutionPreferenceId = outlet.insitutionPreferenceId
        dto.merchantGroupPreferenceId = outlet.merchantGroupPreferenceId
        dto.merchantAcquirerPreferenceId = outlet.merchantAcquirerPreferenceId
        dto.subMerchantPreferenceId = outlet.subMerchantPreferenceId
        dto.outletId = outlet.outletId
        dto.outletName = outlet.outletName
        dto.outletLogo = outlet.outletLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = outlet.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = outlet.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = outlet.address.entityAddressAddressLine3
        dto.entityAddressCity = outlet.address.entityAddressCity
        dto.entityAddressState = outlet.address.entityAddressState
        dto.entityAddressCountry = outlet.address.entityAddressCountry
        dto.entityAddressPostalCode = outlet.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = outlet.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = outlet.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = outlet.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = outlet.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = outlet.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = outlet.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = outlet.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = outlet.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = outlet.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = outlet.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = outlet.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = outlet.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = outlet.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = outlet.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = outlet.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = outlet.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = outlet.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = outlet.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = outlet.info.entityInfoAbbrevation
        dto.entityInfoDescription = outlet.info.entityInfoDescription
        dto.entityInfoLogo = outlet.info.entityInfoLogo
        dto.entityInfoRegion = outlet.info.entityInfoRegion
        dto.entityInfoType = outlet.info.entityInfoType
        dto.entityInfoTimezone = outlet.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = outlet.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = outlet.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = outlet.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = outlet.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = outlet.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = outlet.others.entityOthersMerchantOfflineTxn
        dto.error = outlet.error

        return dto
    }
    fun toSubMerchantDTO(subMerchantAcquirer: SubMerchantAcquirer): SubMerchantAcquirerDTO {
        var dto = SubMerchantAcquirerDTO()
        dto.aggregatorPreferenceId = subMerchantAcquirer.aggregatorPreferenceId
        dto.insitutionPreferenceId = subMerchantAcquirer.insitutionPreferenceId
        dto.merchantGroupPreferenceId = subMerchantAcquirer.merchantGroupPreferenceId
        dto.merchantAcquirerPreferenceId = subMerchantAcquirer.merchantAcquirerPreferenceId
        dto.subMerchantAcquirerId = subMerchantAcquirer.subMerchantAcquirerId
        dto.subMerchantAcquirerName = subMerchantAcquirer.subMerchantAcquirerName
        dto.subMerchantAcquirerLogo = subMerchantAcquirer.subMerchantAcquirerLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = subMerchantAcquirer.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = subMerchantAcquirer.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = subMerchantAcquirer.address.entityAddressAddressLine3
        dto.entityAddressCity = subMerchantAcquirer.address.entityAddressCity
        dto.entityAddressState = subMerchantAcquirer.address.entityAddressState
        dto.entityAddressCountry = subMerchantAcquirer.address.entityAddressCountry
        dto.entityAddressPostalCode = subMerchantAcquirer.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = subMerchantAcquirer.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = subMerchantAcquirer.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = subMerchantAcquirer.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = subMerchantAcquirer.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = subMerchantAcquirer.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = subMerchantAcquirer.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = subMerchantAcquirer.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = subMerchantAcquirer.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = subMerchantAcquirer.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = subMerchantAcquirer.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = subMerchantAcquirer.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = subMerchantAcquirer.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = subMerchantAcquirer.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = subMerchantAcquirer.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = subMerchantAcquirer.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = subMerchantAcquirer.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = subMerchantAcquirer.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = subMerchantAcquirer.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = subMerchantAcquirer.info.entityInfoAbbrevation
        dto.entityInfoDescription = subMerchantAcquirer.info.entityInfoDescription
        dto.entityInfoLogo = subMerchantAcquirer.info.entityInfoLogo
        dto.entityInfoRegion = subMerchantAcquirer.info.entityInfoRegion
        dto.entityInfoType = subMerchantAcquirer.info.entityInfoType
        dto.entityInfoTimezone = subMerchantAcquirer.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = subMerchantAcquirer.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = subMerchantAcquirer.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = subMerchantAcquirer.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = subMerchantAcquirer.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = subMerchantAcquirer.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = subMerchantAcquirer.others.entityOthersMerchantOfflineTxn
        dto.error = subMerchantAcquirer.error

        return dto
    }
    fun toMerchantDTO(merchantAcquirer: MerchantAcquirer): MerchantAcquirerDTO {
        var dto = MerchantAcquirerDTO()
        dto.aggregatorPreferenceId = merchantAcquirer.aggregatorPreferenceId
        dto.insitutionPreferenceId = merchantAcquirer.insitutionPreferenceId
        dto.merchantGroupPreferenceId = merchantAcquirer.merchantGroupPreferenceId
        dto.merchantAcquirerId = merchantAcquirer.merchantAcquirerId
        dto.merchantAcquirerName = merchantAcquirer.merchantAcquirerName
        dto.merchantAcquirerLogo = merchantAcquirer.merchantAcquirerLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = merchantAcquirer.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = merchantAcquirer.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = merchantAcquirer.address.entityAddressAddressLine3
        dto.entityAddressCity = merchantAcquirer.address.entityAddressCity
        dto.entityAddressState = merchantAcquirer.address.entityAddressState
        dto.entityAddressCountry = merchantAcquirer.address.entityAddressCountry
        dto.entityAddressPostalCode = merchantAcquirer.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = merchantAcquirer.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = merchantAcquirer.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = merchantAcquirer.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = merchantAcquirer.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = merchantAcquirer.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = merchantAcquirer.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = merchantAcquirer.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = merchantAcquirer.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = merchantAcquirer.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = merchantAcquirer.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = merchantAcquirer.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = merchantAcquirer.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = merchantAcquirer.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = merchantAcquirer.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = merchantAcquirer.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = merchantAcquirer.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = merchantAcquirer.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = merchantAcquirer.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = merchantAcquirer.info.entityInfoAbbrevation
        dto.entityInfoDescription = merchantAcquirer.info.entityInfoDescription
        dto.entityInfoLogo = merchantAcquirer.info.entityInfoLogo
        dto.entityInfoRegion = merchantAcquirer.info.entityInfoRegion
        dto.entityInfoType = merchantAcquirer.info.entityInfoType
        dto.entityInfoTimezone = merchantAcquirer.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = merchantAcquirer.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = merchantAcquirer.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = merchantAcquirer.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = merchantAcquirer.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = merchantAcquirer.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = merchantAcquirer.others.entityOthersMerchantOfflineTxn
        dto.error = merchantAcquirer.error

        return dto
    }
    fun toMerchantGroupDTO(merchantGroup: MerchantGroup): MerchantGroupDTO {
        var dto = MerchantGroupDTO()
        dto.aggregatorPreferenceId = merchantGroup.aggregatorPreferenceId
        dto.insitutionPreferenceId = merchantGroup.insitutionPreferenceId
        dto.merchantGroupPreferenceId = merchantGroup.merchantGroupPreferenceId
        dto.merchantGroupName = merchantGroup.merchantGroupName
        dto.merchantGroupLogo = merchantGroup.merchantGroupLogo
        dto.merchantGroupStatus = merchantGroup.merchantGroupStatus

        dto.entityAddressAddressLine1 = merchantGroup.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = merchantGroup.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = merchantGroup.address.entityAddressAddressLine3
        dto.entityAddressCity = merchantGroup.address.entityAddressCity
        dto.entityAddressState = merchantGroup.address.entityAddressState
        dto.entityAddressCountry = merchantGroup.address.entityAddressCountry
        dto.entityAddressPostalCode = merchantGroup.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = merchantGroup.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = merchantGroup.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = merchantGroup.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = merchantGroup.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = merchantGroup.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = merchantGroup.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = merchantGroup.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = merchantGroup.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = merchantGroup.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = merchantGroup.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = merchantGroup.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = merchantGroup.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = merchantGroup.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = merchantGroup.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = merchantGroup.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = merchantGroup.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = merchantGroup.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = merchantGroup.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = merchantGroup.info.entityInfoAbbrevation
        dto.entityInfoDescription = merchantGroup.info.entityInfoDescription
        dto.entityInfoLogo = merchantGroup.info.entityInfoLogo
        dto.entityInfoRegion = merchantGroup.info.entityInfoRegion
        dto.entityInfoType = merchantGroup.info.entityInfoType
        dto.entityInfoTimezone = merchantGroup.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = merchantGroup.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = merchantGroup.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = merchantGroup.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = merchantGroup.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = merchantGroup.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = merchantGroup.others.entityOthersMerchantOfflineTxn
        dto.error = merchantGroup.error

        return dto
    }
    fun toInstitutionDTO(institution: Institution): InstitutionDTO {
        var dto = InstitutionDTO()
        dto.aggregatorPreferenceId = institution.aggregatorPreferenceId
        dto.insitutionPreferenceId = institution.insitutionPreferenceId
        dto.institutionId = institution.institutionId
        dto.insitutionPreferenceId = institution.insitutionPreferenceId
        dto.insitutionName = institution.insitutionName
        dto.institutionLogo = institution.institutionLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = institution.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = institution.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = institution.address.entityAddressAddressLine3
        dto.entityAddressCity = institution.address.entityAddressCity
        dto.entityAddressState = institution.address.entityAddressState
        dto.entityAddressCountry = institution.address.entityAddressCountry
        dto.entityAddressPostalCode = institution.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = institution.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = institution.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = institution.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = institution.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = institution.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = institution.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = institution.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = institution.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = institution.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = institution.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = institution.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = institution.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = institution.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = institution.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = institution.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = institution.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = institution.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = institution.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = institution.info.entityInfoAbbrevation
        dto.entityInfoDescription = institution.info.entityInfoDescription
        dto.entityInfoLogo = institution.info.entityInfoLogo
        dto.entityInfoRegion = institution.info.entityInfoRegion
        dto.entityInfoType = institution.info.entityInfoType
        dto.entityInfoTimezone = institution.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = institution.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = institution.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = institution.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = institution.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = institution.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = institution.others.entityOthersMerchantOfflineTxn
        dto.error = institution.error
        return dto
    }
    fun toAggregatorDTO(aggregator: Aggregator): AggregatorDTO {
        var dto = AggregatorDTO()
        dto.type = aggregator.type
        dto.aggregatorPreferenceId = aggregator.aggregatorPreferenceId
        dto.aggregatorName = aggregator.aggregatorName
        dto.aggregatorLogo = aggregator.aggregatorLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = aggregator.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = aggregator.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = aggregator.address.entityAddressAddressLine3
        dto.entityAddressCity = aggregator.address.entityAddressCity
        dto.entityAddressState = aggregator.address.entityAddressState
        dto.entityAddressCountry = aggregator.address.entityAddressCountry
        dto.entityAddressPostalCode = aggregator.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = aggregator.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = aggregator.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = aggregator.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = aggregator.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = aggregator.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = aggregator.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = aggregator.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = aggregator.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = aggregator.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = aggregator.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = aggregator.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = aggregator.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = aggregator.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = aggregator.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = aggregator.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = aggregator.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = aggregator.info.entityInfoAbbrevation
        dto.entityInfoDescription = aggregator.info.entityInfoDescription
        dto.entityInfoLogo = aggregator.info.entityInfoLogo
        dto.entityInfoRegion = aggregator.info.entityInfoRegion
        dto.entityInfoType = aggregator.info.entityInfoType
        dto.entityInfoTimezone = aggregator.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = aggregator.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = aggregator.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = aggregator.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = aggregator.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = aggregator.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = aggregator.others.entityOthersMerchantOfflineTxn
        dto.error = aggregator.error
        return dto
    }
    fun toAggregatorDTOI(aggregator: Institution): AggregatorDTO {
        var dto = AggregatorDTO()
        dto.type = aggregator.type
        dto.aggregatorPreferenceId = aggregator.aggregatorPreferenceId
        dto.insitutionName = aggregator.insitutionName
        dto.institutionId = aggregator.institutionId
        dto.insitutionPreferenceId = aggregator.insitutionPreferenceId
        dto.institutionLogo = aggregator.institutionLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = aggregator.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = aggregator.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = aggregator.address.entityAddressAddressLine3
        dto.entityAddressCity = aggregator.address.entityAddressCity
        dto.entityAddressState = aggregator.address.entityAddressState
        dto.entityAddressCountry = aggregator.address.entityAddressCountry
        dto.entityAddressPostalCode = aggregator.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = aggregator.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = aggregator.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = aggregator.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = aggregator.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = aggregator.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = aggregator.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = aggregator.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = aggregator.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = aggregator.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = aggregator.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = aggregator.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = aggregator.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = aggregator.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = aggregator.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = aggregator.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = aggregator.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = aggregator.info.entityInfoAbbrevation
        dto.entityInfoDescription = aggregator.info.entityInfoDescription
        dto.entityInfoLogo = aggregator.info.entityInfoLogo
        dto.entityInfoRegion = aggregator.info.entityInfoRegion
        dto.entityInfoType = aggregator.info.entityInfoType
        dto.entityInfoTimezone = aggregator.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = aggregator.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = aggregator.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = aggregator.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = aggregator.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = aggregator.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = aggregator.others.entityOthersMerchantOfflineTxn
        dto.error = aggregator.error
        return dto
    }
    fun toAggregatorDTOMg(aggregator: MerchantGroup): AggregatorDTO {
        var dto = AggregatorDTO()
        dto.type = aggregator.type
        dto.aggregatorPreferenceId = aggregator.aggregatorPreferenceId
        dto.merchantGroupName = aggregator.merchantGroupName
        dto.merchantGroupPreferenceId = aggregator.merchantGroupPreferenceId
        dto.institutionId = aggregator.insitutionPreferenceId
        dto.merchantGroupLogo = aggregator.merchantGroupLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = aggregator.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = aggregator.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = aggregator.address.entityAddressAddressLine3
        dto.entityAddressCity = aggregator.address.entityAddressCity
        dto.entityAddressState = aggregator.address.entityAddressState
        dto.entityAddressCountry = aggregator.address.entityAddressCountry
        dto.entityAddressPostalCode = aggregator.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = aggregator.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = aggregator.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = aggregator.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = aggregator.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = aggregator.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = aggregator.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = aggregator.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = aggregator.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = aggregator.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = aggregator.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = aggregator.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = aggregator.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = aggregator.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = aggregator.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = aggregator.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = aggregator.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = aggregator.info.entityInfoAbbrevation
        dto.entityInfoDescription = aggregator.info.entityInfoDescription
        dto.entityInfoLogo = aggregator.info.entityInfoLogo
        dto.entityInfoRegion = aggregator.info.entityInfoRegion
        dto.entityInfoType = aggregator.info.entityInfoType
        dto.entityInfoTimezone = aggregator.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = aggregator.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = aggregator.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = aggregator.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = aggregator.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = aggregator.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = aggregator.others.entityOthersMerchantOfflineTxn
        dto.error = aggregator.error
        return dto
    }
    fun toAggregatorDTOMerchant(aggregator: MerchantAcquirer): AggregatorDTO {
        var dto = AggregatorDTO()
        dto.type = aggregator.type
        dto.aggregatorPreferenceId = aggregator.aggregatorPreferenceId
        dto.merchantAcquirerName = aggregator.merchantAcquirerName
        dto.merchantAcquirerId = aggregator.merchantAcquirerId
        dto.merchantGroupPreferenceId = aggregator.merchantGroupPreferenceId
        dto.institutionId = aggregator.insitutionPreferenceId
        dto.merchantAcquirerLogo = aggregator.merchantAcquirerLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = aggregator.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = aggregator.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = aggregator.address.entityAddressAddressLine3
        dto.entityAddressCity = aggregator.address.entityAddressCity
        dto.entityAddressState = aggregator.address.entityAddressState
        dto.entityAddressCountry = aggregator.address.entityAddressCountry
        dto.entityAddressPostalCode = aggregator.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = aggregator.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = aggregator.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = aggregator.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = aggregator.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = aggregator.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = aggregator.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = aggregator.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = aggregator.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = aggregator.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = aggregator.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = aggregator.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = aggregator.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = aggregator.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = aggregator.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = aggregator.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = aggregator.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = aggregator.info.entityInfoAbbrevation
        dto.entityInfoDescription = aggregator.info.entityInfoDescription
        dto.entityInfoLogo = aggregator.info.entityInfoLogo
        dto.entityInfoRegion = aggregator.info.entityInfoRegion
        dto.entityInfoType = aggregator.info.entityInfoType
        dto.entityInfoTimezone = aggregator.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = aggregator.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = aggregator.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = aggregator.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = aggregator.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = aggregator.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = aggregator.others.entityOthersMerchantOfflineTxn
        dto.error = aggregator.error
        return dto
    }
    fun toAggregatorDTOSubM(aggregator: SubMerchantAcquirer): AggregatorDTO {
        var dto = AggregatorDTO()
        dto.type = aggregator.type
        dto.aggregatorPreferenceId = aggregator.aggregatorPreferenceId
        dto.subMerchantAcquirerName = aggregator.subMerchantAcquirerName
        dto.subMerchantAcquirerId = aggregator.subMerchantAcquirerId
        dto.institutionId = aggregator.insitutionPreferenceId
        dto.merchantGroupPreferenceId = aggregator.merchantGroupPreferenceId
        dto.merchantAcquirerId = aggregator.merchantAcquirerPreferenceId
        dto.subMerchantAcquirerLogo = aggregator.subMerchantAcquirerLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = aggregator.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = aggregator.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = aggregator.address.entityAddressAddressLine3
        dto.entityAddressCity = aggregator.address.entityAddressCity
        dto.entityAddressState = aggregator.address.entityAddressState
        dto.entityAddressCountry = aggregator.address.entityAddressCountry
        dto.entityAddressPostalCode = aggregator.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = aggregator.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = aggregator.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = aggregator.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = aggregator.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = aggregator.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = aggregator.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = aggregator.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = aggregator.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = aggregator.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = aggregator.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = aggregator.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = aggregator.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = aggregator.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = aggregator.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = aggregator.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = aggregator.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = aggregator.info.entityInfoAbbrevation
        dto.entityInfoDescription = aggregator.info.entityInfoDescription
        dto.entityInfoLogo = aggregator.info.entityInfoLogo
        dto.entityInfoRegion = aggregator.info.entityInfoRegion
        dto.entityInfoType = aggregator.info.entityInfoType
        dto.entityInfoTimezone = aggregator.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = aggregator.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = aggregator.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = aggregator.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = aggregator.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = aggregator.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = aggregator.others.entityOthersMerchantOfflineTxn
        dto.error = aggregator.error
        return dto
    }

    fun toAggregatorDTOOutlet(aggregator: Outlet): AggregatorDTO {
        var dto = AggregatorDTO()
        dto.type = aggregator.type
        dto.aggregatorPreferenceId = aggregator.aggregatorPreferenceId
        dto.insitutionName = aggregator.outletName
        dto.outletId = aggregator.outletId
        dto.institutionId = aggregator.insitutionPreferenceId
        dto.merchantGroupPreferenceId = aggregator.merchantGroupPreferenceId
        dto.merchantAcquirerId = aggregator.merchantAcquirerPreferenceId
        dto.subMerchantAcquirerId = aggregator.subMerchantPreferenceId
        dto.outletLogo = aggregator.outletLogo
        // dto.outletStatus=outlet.outletStatus
        dto.entityAddressAddressLine1 = aggregator.address.entityAddressAddressLine1
        dto.entityAddressAddressLine2 = aggregator.address.entityAddressAddressLine2
        dto.entityAddressAddressLine3 = aggregator.address.entityAddressAddressLine3
        dto.entityAddressCity = aggregator.address.entityAddressCity
        dto.entityAddressState = aggregator.address.entityAddressState
        dto.entityAddressCountry = aggregator.address.entityAddressCountry
        dto.entityAddressPostalCode = aggregator.address.entityAddressPostalCode
        dto.entityAdminDetailsFirstName = aggregator.adminDetails.entityAdminDetailsFirstName
        dto.entityAdminDetailsMiddleName = aggregator.adminDetails.entityAdminDetailsMiddleName
        dto.entityAdminDetailsLastName = aggregator.adminDetails.entityAdminDetailsLastName
        dto.entityAdminDetailsMobileNumber = aggregator.adminDetails.entityAdminDetailsMobileNumber
        dto.entityAdminDetailsEmailId = aggregator.adminDetails.entityAdminDetailsEmailId
        dto.entityAdminDetailsDepartment = aggregator.adminDetails.entityAdminDetailsDepartment
        dto.entityBankDetailsBankAccountNumber = aggregator.bankDetails.entityBankDetailsBankAccountNumber
        dto.entityBankDetailsBankHolderName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBankName = aggregator.bankDetails.entityBankDetailsBankName
        dto.entityBankDetailsBranchCode = aggregator.bankDetails.entityBankDetailsBranchCode
        dto.entityBankDetailsBranchLocation = aggregator.bankDetails.entityBankDetailsBranchLocation
        dto.entityContactDetailsFirstName = aggregator.contactDetails.entityContactDetailsFirstName
        dto.entityContactDetailsMiddleName = aggregator.contactDetails.entityContactDetailsMiddleName
        dto.entityContactDetailsLastName = aggregator.contactDetails.entityContactDetailsLastName
        dto.entityContactDetailsEmailId = aggregator.contactDetails.entityContactDetailsEmailId
        dto.entityContactDetailsMobileNumber = aggregator.contactDetails.entityContactDetailsMobileNumber
        dto.entityContactDetailsDesignation = aggregator.contactDetails.entityContactDetailsDesignation
        dto.entityContactDetailsDepartment = aggregator.contactDetails.entityContactDetailsDepartment
        dto.entityInfoAbbrevation = aggregator.info.entityInfoAbbrevation
        dto.entityInfoDescription = aggregator.info.entityInfoDescription
        dto.entityInfoLogo = aggregator.info.entityInfoLogo
        dto.entityInfoRegion = aggregator.info.entityInfoRegion
        dto.entityInfoType = aggregator.info.entityInfoType
        dto.entityInfoTimezone = aggregator.info.entityInfoTimezone
        dto.entityInfoDefaultDigitalCurrency = aggregator.info.entityInfoDefaultDigitalCurrency
        dto.entityInfoBaseFiatCurrency = aggregator.info.entityInfoBaseFiatCurrency
        dto.entityOthersActivationDate = aggregator.others.entityOthersActivationDate
        dto.entityOthersCustomerOfflineTxn = aggregator.others.entityOthersCustomerOfflineTxn
        dto.entityOthersApprovalWorkFlow = aggregator.others.entityOthersApprovalWorkFlow
        dto.entityOthersMerchantOfflineTxn = aggregator.others.entityOthersMerchantOfflineTxn
        dto.error = aggregator.error
        return dto
    }
}
