version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_REDIS_HOST: redis
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      - 5432
  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
